const STORAGE_KEY='droneInterviewFormalV2';
const CRITERIA=['內容完整','邏輯條理','職務連結','安全責任','表達台風'];
const roundLabels={warmup:'第一輪｜暖身面試',scenario:'第二輪｜情境挑戰',career:'第三輪｜職類面試',offer:'第四輪｜Offer談判',pk:'最終關｜面試PK'};
const careerLabels={pilot:'無人機操作／飛手',media:'空拍攝影／影像製作',inspection:'巡檢／測繪／工程應用',project:'專案行政／業務助理'};
const $=id=>document.getElementById(id);
const initialTeams=()=>[1,2,3,4].map((n)=>({name:`第${n}組`,members:['學員A','學員B','學員C','學員D'],member:0,score:0,attempts:0}));
let state={version:2,teams:initialTeams(),activeTeam:0,round:'warmup',career:'pilot',answerSeconds:90,seconds:90,timerRunning:false,current:null,currentToken:null,currentSaved:false,used:{},criteria:[3,3,3,3,3],attempts:[],logs:[],history:[],startedAt:new Date().toISOString()};
let timerId=null,toastId=null;
function safeSave(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saveIndicator').textContent='● 已自動保存';return true}catch(e){$('saveIndicator').textContent='⚠ 無法保存';return false}}
function safeLoad(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return null;const s=JSON.parse(raw);return s&&s.version===2?s:null}catch(e){return null}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function snapshot(label){state.history=state.history||[];state.history.push({label,state:clone({...state,history:[]})});if(state.history.length>20)state.history.shift()}
function undo(){if(!state.history||!state.history.length){toast('沒有可復原的動作');return}const item=state.history.pop();const history=state.history;state={...item.state,history};stopTimer();renderAll();safeSave();toast(`已復原：${item.label}`)}
function toast(text){clearTimeout(toastId);$('toast').textContent=text;$('toast').classList.add('show');toastId=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function openOverlay(id){$(''+id).classList.add('open')}function closeOverlay(id){$(''+id).classList.remove('open')}
function log(text,type='info'){const time=new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',second:'2-digit'});state.logs.unshift({time,text,type,at:new Date().toISOString()});if(state.logs.length>300)state.logs.length=300;renderLog();safeSave()}
function roundPool(){const r=state.round;if(r==='offer')return OFFERS.map((question,i)=>({id:`O${i+1}`,category:'Offer談判',question,intent:'確認薪資、到職條件與職涯判斷。',hint:'先確認職務內容與完整條件，再提出有依據、可協商的回答。'}));if(r==='warmup')return QUESTIONS.filter(q=>q.id<=10);if(r==='scenario')return QUESTIONS.filter(q=>(q.id>=21&&q.id<=30)||(q.id>=51&&q.id<=80));if(r==='pk')return QUESTIONS.filter(q=>(q.id>=71&&q.id<=80)||(q.id>=91&&q.id<=100)||[22,27,57,62].includes(q.id));const map={pilot:q=>(q.id>=11&&q.id<=30)||(q.id>=51&&q.id<=60),media:q=>(q.id>=21&&q.id<=40)||(q.id>=61&&q.id<=70),inspection:q=>(q.id>=21&&q.id<=30)||(q.id>=41&&q.id<=70),project:q=>(q.id>=61&&q.id<=100)};return QUESTIONS.filter(map[state.career])}
function usedKey(){return `${state.round}:${state.career}`}
function drawQuestion(isChange=false){snapshot(isChange?'換題':'抽題');const pool=roundPool();const key=usedKey();state.used[key]=state.used[key]||[];let available=pool.filter(q=>!state.used[key].includes(String(q.id)));if(!available.length){state.used[key]=[];available=pool;toast('本題組已全部抽完，重新洗牌')}const q=available[Math.floor(Math.random()*available.length)];state.used[key].push(String(q.id));state.current=q;state.currentToken=`${Date.now()}-${Math.random().toString(36).slice(2)}`;state.currentSaved=false;state.criteria=[3,3,3,3,3];resetTimer(false);log(`${isChange?'換題':'抽題'}｜${activeTeam().name}｜${activePlayer()}｜${q.category}：${q.question}`);renderQuestion(true);renderCriteria();safeSave()}
function activeTeam(){return state.teams[state.activeTeam]}function activePlayer(){return activeTeam().members[activeTeam().member]}
function roleName(offset){const t=activeTeam();return t.members[(t.member+offset)%4]}
function setActiveTeam(i){if(i===state.activeTeam)return;snapshot('切換小組');state.activeTeam=i;stopTimer();resetTimer(false);renderAll();safeSave()}
function nextRole(){snapshot('下一位');stopTimer();const t=activeTeam();t.member=(t.member+1)%4;if(t.member===0)state.activeTeam=(state.activeTeam+1)%state.teams.length;state.current=null;state.currentToken=null;state.currentSaved=false;state.criteria=[3,3,3,3,3];resetTimer(false);log(`角色輪替｜目前 ${activeTeam().name}｜應徵者：${activePlayer()}`);renderAll();toast('角色已自動輪替，請抽下一題')}
function renderTeams(){$('teams').innerHTML=state.teams.map((t,i)=>{const pct=Math.min(100,(t.attempts/4)*100);return `<div class="team ${i===state.activeTeam?'active':''}" data-team="${i}"><div class="team-head"><span class="team-name">${escapeHtml(t.name)}</span><span class="team-score">${t.score}</span></div><div class="members"><span class="role-badge">應徵者</span>${escapeHtml(t.members[t.member])}<br><span class="role-badge">面試官</span>${escapeHtml(t.members[(t.member+1)%4])}　<span class="role-badge">觀察</span>${escapeHtml(t.members[(t.member+2)%4])}<br><span class="role-badge">紀錄</span>${escapeHtml(t.members[(t.member+3)%4])}｜已評分 ${t.attempts} 題</div><div class="team-progress"><span style="width:${pct}%"></span></div></div>`}).join('');document.querySelectorAll('[data-team]').forEach(el=>el.onclick=()=>setActiveTeam(Number(el.dataset.team)));renderStatus();renderRanking()}
function renderStatus(){$('roundStatus').textContent=roundLabels[state.round];$('teamStatus').textContent=activeTeam().name;$('playerStatus').textContent=`應徵者：${activePlayer()}`;$('roundSelect').value=state.round;$('careerSelect').value=state.career;$('answerSeconds').value=String(state.answerSeconds);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.round===state.round));$('careerSelect').disabled=state.round!=='career'}
function renderQuestion(animate=false){const q=state.current;if(!q){$('category').textContent='準備開始';$('question').textContent='請由老師選擇輪次，按下「自動抽題」';$('intent').innerHTML='<b>企業想確認：</b>系統將顯示面試官觀察重點。';$('hint').innerHTML='<b>高分回答：</b>系統將顯示回答架構提示。';$('questionNo').textContent='題號：—';$('attemptInfo').textContent='本題尚未評分';$('unsavedBadge').textContent='尚未抽題';return}$('category').textContent=q.category;$('question').textContent=q.question;$('intent').innerHTML=`<b>企業想確認：</b>${escapeHtml(q.intent)}`;$('hint').innerHTML=`<b>高分回答：</b>${escapeHtml(q.hint)}`;$('questionNo').textContent=`題號：${q.id}`;$('attemptInfo').textContent=state.currentSaved?'本題成績已儲存':'本題尚未評分';$('unsavedBadge').textContent=state.currentSaved?'✓ 已評分':'● 待評分';$('unsavedBadge').style.color=state.currentSaved?'var(--green)':'var(--red)';if(animate){$('questionCard').classList.remove('draw');void $('questionCard').offsetWidth;$('questionCard').classList.add('draw')}}
function renderCriteria(){$('criteria').innerHTML=CRITERIA.map((name,ci)=>`<div class="criterion"><div class="criterion-head"><span>${name}</span><span>${state.criteria[ci]}分</span></div><div class="score-options">${[1,2,3,4,5].map(n=>`<button class="score-option ${state.criteria[ci]===n?'active':''}" data-ci="${ci}" data-score="${n}">${n}</button>`).join('')}</div></div>`).join('');document.querySelectorAll('.score-option').forEach(b=>b.onclick=()=>{state.criteria[Number(b.dataset.ci)]=Number(b.dataset.score);renderCriteria();safeSave()});$('scoreTotal').textContent=state.criteria.reduce((a,b)=>a+b,0)}
function applyPreset(n){state.criteria=[n,n,n,n,n];renderCriteria();safeSave()}
function saveScore(){if(!state.current){toast('請先抽題');return}snapshot('儲存成績');const total=state.criteria.reduce((a,b)=>a+b,0);const comment=[$('commentSelect').value,$('customComment').value.trim()].filter(Boolean).join('｜');let attempt=state.attempts.find(a=>a.token===state.currentToken);if(attempt){const team=state.teams[attempt.teamIndex];team.score+=total-attempt.total;attempt.criteria=[...state.criteria];attempt.total=total;attempt.comment=comment;attempt.updatedAt=new Date().toISOString();log(`更新評分｜${team.name}｜${attempt.player}｜${total}/25`)}else{attempt={token:state.currentToken,time:new Date().toLocaleString('zh-TW'),teamIndex:state.activeTeam,team:activeTeam().name,player:activePlayer(),round:roundLabels[state.round],career:careerLabels[state.career],questionId:state.current.id,category:state.current.category,question:state.current.question,criteria:[...state.criteria],total,comment};state.attempts.push(attempt);activeTeam().score+=total;activeTeam().attempts+=1;log(`儲存評分｜${activeTeam().name}｜${activePlayer()}｜${total}/25｜${comment}`)}state.currentSaved=true;$('customComment').value='';renderAll();safeSave();toast(`已儲存 ${total} 分`)}
function renderRanking(){const sorted=state.teams.map((t,i)=>({...t,index:i})).sort((a,b)=>b.score-a.score||a.index-b.index);$('ranking').innerHTML=sorted.map((t,i)=>`<div class="rank-item"><span class="rank-no">${i+1}</span><b>${escapeHtml(t.name)}</b><span class="rank-score">${t.score}分</span></div>`).join('')}
function renderLog(){$('log').innerHTML=state.logs.length?state.logs.map(x=>`<div class="log-entry"><b>${escapeHtml(x.time)}</b>　${escapeHtml(x.text)}</div>`).join(''):'<div class="empty">尚無紀錄</div>'}
function showChallenge(title,text){$('challengeTitle').textContent=title;$('challengeText').textContent=text;openOverlay('challengeOverlay');log(`${title}｜${text}`)}
function resetTimer(save=true){stopTimer();state.seconds=Number(state.answerSeconds);renderTimer();if(save)safeSave()}function renderTimer(){const s=Math.max(0,state.seconds);$('timer').textContent=s===0?'時間到':`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;$('timer').classList.toggle('warning',s>0&&s<=15)}function startTimer(){if(state.seconds<=0)resetTimer(false);stopTimer();state.timerRunning=true;timerId=setInterval(()=>{state.seconds-=1;renderTimer();if(state.seconds<=0){stopTimer();beep(880,.35);log('⏰ 回答時間結束');toast('回答時間到')}if(state.seconds%5===0)safeSave()},1000);safeSave()}function stopTimer(){clearInterval(timerId);timerId=null;state.timerRunning=false}function toggleTimer(){state.timerRunning?stopTimer():startTimer();safeSave()}function adjustTimer(n){state.seconds=Math.max(0,state.seconds+n);renderTimer();safeSave()}
function beep(freq=680,duration=.12){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=freq;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.start();o.stop(ctx.currentTime+duration)}catch(e){}}
function renderSetup(){$('setupGrid').innerHTML=state.teams.map((t,i)=>`<div class="setup-team"><h3>第${i+1}組</h3><label>小組名稱</label><input data-team-name="${i}" value="${escapeAttr(t.name)}"><div class="member-grid">${t.members.map((m,mi)=>`<div><label>學員${mi+1}</label><input data-member="${i}-${mi}" value="${escapeAttr(m)}"></div>`).join('')}</div></div>`).join('')}function saveSetup(){snapshot('學員設定');document.querySelectorAll('[data-team-name]').forEach(inp=>state.teams[Number(inp.dataset.teamName)].name=inp.value.trim()||`第${Number(inp.dataset.teamName)+1}組`);document.querySelectorAll('[data-member]').forEach(inp=>{const [ti,mi]=inp.dataset.member.split('-').map(Number);state.teams[ti].members[mi]=inp.value.trim()||`學員${String.fromCharCode(65+mi)}`});closeOverlay('setupOverlay');renderAll();safeSave();toast('學員設定已儲存')}
function setRound(r){if(state.round===r)return;snapshot('切換輪次');state.round=r;state.current=null;state.currentSaved=false;stopTimer();resetTimer(false);renderAll();safeSave()}
function setCareer(c){state.career=c;if(state.round==='career'){state.current=null;state.currentSaved=false;renderQuestion()}safeSave()}
function exportCSV(){const rows=[['無人機求職任務｜面試紀錄'],['匯出時間',new Date().toLocaleString('zh-TW')],[],['時間','組別','應徵者','輪次','求職方向','題號','類別','題目',...CRITERIA,'總分','評語'],...state.attempts.map(a=>[a.time,a.team,a.player,a.round,a.career,a.questionId,a.category,a.question,...a.criteria,a.total,a.comment]),[],['組別','累計分數','完成題數'],...state.teams.map(t=>[t.name,t.score,t.attempts])];downloadText('\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\n'),'無人機求職任務_面試成績.csv','text/csv;charset=utf-8');toast('CSV已匯出')}function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}function backupJSON(){downloadText(JSON.stringify(state,null,2),'無人機求職任務_課程備份.json','application/json');toast('備份檔已下載')}function downloadText(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importJSON(file){const reader=new FileReader();reader.onload=()=>{try{const s=JSON.parse(reader.result);if(!s||s.version!==2||!Array.isArray(s.teams))throw new Error();snapshot('匯入前狀態');state=s;state.history=state.history||[];stopTimer();renderAll();safeSave();toast('備份已成功匯入')}catch(e){toast('備份檔格式不正確')}};reader.readAsText(file)}
function resetAll(){if($('resetConfirm').value.trim()!=='重設'){toast('請輸入「重設」');return}stopTimer();localStorage.removeItem(STORAGE_KEY);state={version:2,teams:initialTeams(),activeTeam:0,round:'warmup',career:'pilot',answerSeconds:90,seconds:90,timerRunning:false,current:null,currentToken:null,currentSaved:false,used:{},criteria:[3,3,3,3,3],attempts:[],logs:[],history:[],startedAt:new Date().toISOString()};$('resetConfirm').value='';closeOverlay('resetOverlay');renderAll();safeSave();toast('全部資料已重設')}
function presentation(on){document.body.classList.toggle('presentation',on??!document.body.classList.contains('presentation'));$('presentationBtn').textContent=document.body.classList.contains('presentation')?'退出投影':'投影模式'}
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){toast('瀏覽器未允許全螢幕')}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(s){return escapeHtml(s)}
function renderAll(){renderStatus();renderTeams();renderQuestion();renderCriteria();renderRanking();renderLog();renderTimer();$('undoBtn').disabled=!state.history?.length}
function enterApp(resume=false){if(resume){const loaded=safeLoad();if(loaded)state=loaded}$('splash').classList.add('hidden');$('app').classList.remove('hidden');stopTimer();state.timerRunning=false;renderAll();safeSave();if(!resume){renderSetup();openOverlay('setupOverlay')}toast(resume?'已載入上次進度':'免登入模式已啟動')}
function hasSaved(){return !!safeLoad()}
$('newGameBtn').onclick=()=>{const old=safeLoad();if(old&&old.attempts?.length&&!confirm('開始新課程會覆蓋瀏覽器中的上次進度，確定繼續？'))return;localStorage.removeItem(STORAGE_KEY);enterApp(false)};$('resumeBtn').onclick=()=>enterApp(true);$('splashHelpBtn').onclick=()=>openOverlay('helpOverlay');$('setupBtn').onclick=()=>{renderSetup();openOverlay('setupOverlay')};$('saveSetupBtn').onclick=saveSetup;$('helpBtn').onclick=()=>openOverlay('helpOverlay');$('drawBtn').onclick=()=>drawQuestion(false);$('changeBtn').onclick=()=>drawQuestion(true);$('nextRoleBtn').onclick=nextRole;$('undoBtn').onclick=undo;$('followBtn').onclick=()=>showChallenge('面試官追問',FOLLOWUPS[Math.floor(Math.random()*FOLLOWUPS.length)]);$('eventBtn').onclick=()=>showChallenge('突發事件卡',EVENTS[Math.floor(Math.random()*EVENTS.length)]);$('closeChallenge').onclick=()=>closeOverlay('challengeOverlay');$('startTimerBtn').onclick=startTimer;$('pauseTimerBtn').onclick=()=>{stopTimer();safeSave()};$('resetTimerBtn').onclick=()=>resetTimer();$('minusTimerBtn').onclick=()=>adjustTimer(-10);$('plusTimerBtn').onclick=()=>adjustTimer(10);$('saveScoreBtn').onclick=saveScore;$('exportBtn').onclick=exportCSV;$('backupBtn').onclick=backupJSON;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files[0])importJSON(e.target.files[0]);e.target.value=''};$('resetBtn').onclick=()=>openOverlay('resetOverlay');$('confirmResetBtn').onclick=resetAll;$('printBtn').onclick=()=>window.print();$('clearLogBtn').onclick=()=>{snapshot('清除紀錄顯示');state.logs=[];renderLog();safeSave();toast('畫面紀錄已清除，成績仍保留')};$('presentationBtn').onclick=()=>presentation();$('fullscreenBtn').onclick=fullscreen;$('roundSelect').onchange=e=>setRound(e.target.value);$('careerSelect').onchange=e=>setCareer(e.target.value);$('answerSeconds').onchange=e=>{state.answerSeconds=Number(e.target.value);resetTimer();};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>setRound(t.dataset.round));document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>applyPreset(Number(b.dataset.preset)));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));$('pDraw').onclick=()=>drawQuestion(false);$('pTimer').onclick=toggleTimer;$('pFollow').onclick=()=>$('followBtn').click();$('pNext').onclick=nextRole;$('pExit').onclick=()=>presentation(false);
document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o&&o.id!=='resetOverlay')closeOverlay(o.id)}));
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(e.key===' '){e.preventDefault();toggleTimer()}else if(k==='d')drawQuestion(false);else if(k==='n')nextRole();else if(k==='f')$('followBtn').click();else if(k==='e')$('eventBtn').click();else if(k==='s')saveScore();else if(k==='p')presentation();else if(['1','2','3','4','5'].includes(k))applyPreset(Number(k));else if(e.key==='Escape')document.querySelectorAll('.overlay.open').forEach(o=>closeOverlay(o.id))});
window.addEventListener('beforeunload',safeSave);document.addEventListener('visibilitychange',()=>{if(document.hidden){stopTimer();safeSave()}});
if(hasSaved())$('resumeBtn').classList.remove('hidden');
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));