/* ProjectOps ERP｜Orchestrator Core v1
 * 串連層：專案主檔 → 政府標案 / 自辦課程 → 場次 → 招生 → 任務 → CRM。
 */
function handleProjectOpsOrchestratorAction(action,data){data=data||{};try{if(action==='project.create'||action==='專案建立')return PO_Project_create(data);if(action==='project.query'||action==='專案查詢')return PO_Project_query(data);if(action==='project.createEvent'||action==='專案建立場次')return PO_Project_createEvent(data);if(action==='project.createRegistration'||action==='專案建立招生')return PO_Project_createRegistration(data);if(action==='project.bootstrap'||action==='專案初始化')return PO_Project_bootstrap(data);if(action==='project.dashboard'||action==='專案總覽')return PO_Project_dashboard(data);return null;}catch(err){return{success:false,message:'ProjectOps Orchestrator 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var PROJECTOPS_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsOrchestratorAction(action,data);if(handled)return handled;return PROJECTOPS_PREV_GATEWAY(action,data);};}
function PO_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function PO_ensure(){GovOpsProduct_ensureSheet('00_專案主檔',['專案ID','tenantId','案源類型','專案名稱','專案狀態','主辦單位','合作單位','專案類型','開始日期','結束日期','預算金額','營收目標','實際收入','實際支出','負責人','標案ID','課程ID','建立時間','更新時間','備註']);GovOpsProduct_ensureSheet('06_自辦課程主檔',['課程ID','tenantId','專案ID','課程名稱','課程類型','課程定價','早鳥價','優惠價','招生目標人數','最低開課人數','開課成本','營收目標','付款方式','退費規則','建立時間','更新時間','備註']);}
function PO_Project_create(data){PO_ensure();var source=data.案源類型||data.sourceType||'自辦課程';var projectId=data.專案ID||data.projectId||'PROJ-'+Utilities.formatDate(new Date(),'Asia/Taipei','yyyy')+'-'+Utilities.getUuid().slice(0,6);var row={專案ID:projectId,tenantId:data.tenantId||'TENANT-DEMO',案源類型:source,專案名稱:data.專案名稱||data.projectName||data.標案名稱||data.課程名稱||'',專案狀態:data.專案狀態||'進行中',主辦單位:data.主辦單位||data.機關名稱||'',合作單位:data.合作單位||'',專案類型:data.專案類型||data.課程類型||'',開始日期:data.開始日期||'',結束日期:data.結束日期||'',預算金額:Number(data.預算金額||0),營收目標:Number(data.營收目標||0),實際收入:Number(data.實際收入||0),實際支出:Number(data.實際支出||0),負責人:data.負責人||data.userId||'',標案ID:data.標案ID||'',課程ID:data.課程ID||'',建立時間:PO_now(),更新時間:PO_now(),備註:data.備註||''};GovOpsProduct_append('00_專案主檔',row);var child=null;if(source==='政府標案')child=PO_createTenderRecord(row,data);else child=PO_createCourseRecord(row,data);return{success:true,message:'專案已建立並完成案源初始化。',data:{project:row,child:child}}}
function PO_createTenderRecord(project,data){try{if(typeof GOTenderPool_create==='function')return GOTenderPool_create(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,標案名稱:project.專案名稱,機關名稱:project.主辦單位}));}catch(e){}return{success:false,message:'標案池模組尚未可用，已先建立專案主檔。'}}
function PO_createCourseRecord(project,data){var courseId=data.課程ID||'COURSE-'+Utilities.getUuid().slice(0,8);var row={課程ID:courseId,tenantId:project.tenantId,專案ID:project.專案ID,課程名稱:data.課程名稱||project.專案名稱,課程類型:data.課程類型||project.專案類型,課程定價:Number(data.課程定價||0),早鳥價:Number(data.早鳥價||0),優惠價:Number(data.優惠價||0),招生目標人數:Number(data.招生目標人數||0),最低開課人數:Number(data.最低開課人數||0),開課成本:Number(data.開課成本||0),營收目標:Number(data.營收目標||project.營收目標||0),付款方式:data.付款方式||'',退費規則:data.退費規則||'',建立時間:PO_now(),更新時間:PO_now(),備註:data.備註||''};GovOpsProduct_append('06_自辦課程主檔',row);try{var p=PO_findProject(project.tenantId,project.專案ID);if(p)GovOpsProduct_update('00_專案主檔',p._row,{課程ID:courseId,更新時間:PO_now()});}catch(e){}return{success:true,message:'自辦課程主檔已建立。',data:row}}
function PO_Project_query(data){PO_ensure();var keyword=String(data.keyword||data.關鍵字||data.專案ID||'').trim();var rows=GovOpsProduct_readRows('00_專案主檔').filter(function(r){if(data.tenantId&&String(r.tenantId||'')!==String(data.tenantId))return false;if(data.案源類型&&String(r.案源類型||'')!==String(data.案源類型))return false;if(!keyword)return true;return JSON.stringify(r).indexOf(keyword)>=0;});return{success:true,message:'專案查詢完成。',data:{total:rows.length,summary:PO_countProjects(rows),rows:rows.slice(0,500)}}}
function PO_Project_createEvent(data){PO_ensure();var project=PO_findProject(data.tenantId,data.專案ID||data.projectId);if(!project)return{success:false,message:'找不到專案。',data:{}};var payload=Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID,課程ID:project.課程ID,標案名稱:project.專案名稱,活動名稱:data.活動名稱||project.專案名稱,備註:(data.備註||'')+'｜由ProjectOps專案建立場次'});var result=null;if(typeof GovOpsTenderExecutionEvent_create==='function')result=GovOpsTenderExecutionEvent_create(payload);else result={success:false,message:'場次模組尚未可用。',data:payload};return{success:true,message:'專案場次建立流程完成。',data:{project:project,event:result}}}
function PO_Project_createRegistration(data){PO_ensure();var project=PO_findProject(data.tenantId,data.專案ID||data.projectId);if(!project)return{success:false,message:'找不到專案。',data:{}};var payload=Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID,活動名稱:data.活動名稱||project.專案名稱});var result=null;if(typeof GovOpsReg_Setting_create==='function')result=GovOpsReg_Setting_create(payload);else result={success:false,message:'招生模組尚未可用。',data:payload};return{success:true,message:'專案招生建立流程完成。',data:{project:project,registration:result}}}
function PO_Project_bootstrap(data){var created=PO_Project_create(data);if(!created.success)return created;var project=created.data.project;var event=PO_Project_createEvent(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID}));var reg=PO_Project_createRegistration(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,場次ID:data.場次ID||''}));return{success:true,message:'專案初始化完成。',data:{project:project,event:event,registration:reg}}}
function PO_Project_dashboard(data){var q=PO_Project_query(data).data;return{success:true,message:'專案總覽完成。',data:q.summary}}
function PO_findProject(tenantId,projectId){try{return GovOpsProduct_readRows('00_專案主檔').find(function(r){return String(r.tenantId||'')===String(tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(projectId||'')})||null;}catch(e){return null}}
function PO_countProjects(rows){var out={total:rows.length,政府標案:0,自辦課程:0,合作課程:0,企業委託:0,政府補助案:0,其他:0};rows.forEach(function(r){var s=String(r.案源類型||'其他');out[s]=(out[s]||0)+1;});return out;}
