/* ProjectOps ERP｜Project Detail Runtime v1
 * 單一專案營運總控：專案 → 場次 → 招生 → 報名 → 名冊 → CRM → 任務 → 通知 → 財務 → 結案
 */
function handleProjectOpsProjectDetailAction(action,data){data=data||{};try{if(action==='project.detail.get'||action==='專案詳情')return PODetail_get(data);if(action==='project.detail.status'||action==='專案營運狀態')return PODetail_status(data);if(action==='project.detail.timeline'||action==='專案時間軸')return PODetail_timeline(data);return null;}catch(err){return{success:false,message:'專案詳情 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var PROJECTOPS_PREV_DETAIL_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsProjectDetailAction(action,data);if(handled)return handled;return PROJECTOPS_PREV_DETAIL_GATEWAY(action,data);};}
function PODetail_ensure(){if(typeof PO_ensure==='function')PO_ensure();}
function PODetail_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function PODetail_matchProject(row,project){if(!row||!project)return false;var pid=String(project.專案ID||'');var tid=String(project.標案ID||'');var cid=String(project.課程ID||'');return String(row.專案ID||'')===pid||(tid&&String(row.標案ID||'')===tid)||(cid&&String(row.課程ID||'')===cid)}
function PODetail_findProject(data){PODetail_ensure();var tenantId=data.tenantId||'TENANT-DEMO';var projectId=data.專案ID||data.projectId||'';var keyword=String(data.keyword||data.關鍵字||'').trim();var rows=PODetail_read('00_專案主檔').filter(function(r){if(String(r.tenantId||'')!==String(tenantId))return false;if(projectId)return String(r.專案ID||'')===String(projectId);if(keyword)return JSON.stringify(r).indexOf(keyword)>=0;return false;});return rows[0]||null;}
function PODetail_get(data){var project=PODetail_findProject(data);if(!project)return{success:false,message:'找不到專案，請提供專案ID。',data:{}};var detail={project:project,tender:[],course:[],events:[],registrations:[],roster:[],participants:[],tasks:[],email:[],files:[],finance:[],closing:[]};detail.tender=PODetail_read('01_標案池').filter(function(r){return PODetail_matchProject(r,project)});detail.course=PODetail_read('06_自辦課程主檔').filter(function(r){return PODetail_matchProject(r,project)});detail.events=PODetail_read('74_履約活動場次').filter(function(r){return PODetail_matchProject(r,project)});detail.registrations=PODetail_read('86_報名資料').filter(function(r){return PODetail_matchProject(r,project)});detail.roster=PODetail_read('88_學員名冊').filter(function(r){return PODetail_matchProject(r,project)});detail.participants=PODetail_read('97_學員參與歷程').filter(function(r){return PODetail_matchProject(r,project)});detail.tasks=PODetail_read('90_履約工作任務').filter(function(r){return PODetail_matchProject(r,project)});detail.email=PODetail_read('103_Email通知佇列').filter(function(r){return PODetail_matchProject(r,project)});detail.files=PODetail_read('96_檔案中心').filter(function(r){return PODetail_matchProject(r,project)});detail.finance=PODetail_read('記帳明細').filter(function(r){return PODetail_matchProject(r,project)});detail.closing=PODetail_read('結案報告').filter(function(r){return PODetail_matchProject(r,project)});return{success:true,message:'專案詳情讀取完成。',data:{summary:PODetail_summary(detail),detail:detail}}}
function PODetail_status(data){var got=PODetail_get(data);if(!got.success)return got;return{success:true,message:'專案營運狀態完成。',data:got.data.summary}}
function PODetail_summary(detail){var reg=detail.registrations||[];var tasks=detail.tasks||[];var email=detail.email||[];return{專案ID:detail.project.專案ID,案源類型:detail.project.案源類型,專案名稱:detail.project.專案名稱,場次數:(detail.events||[]).length,報名數:reg.length,已錄取:reg.filter(function(r){return String(r.錄取狀態||'')==='已錄取'}).length,待審核:reg.filter(function(r){return String(r.錄取狀態||'').indexOf('待')>=0||String(r.審核狀態||'').indexOf('待')>=0}).length,名冊數:(detail.roster||[]).length,任務數:tasks.length,未完成任務:tasks.filter(function(t){return['待指派','待處理','執行中','逾期'].indexOf(String(t.任務狀態||''))>=0}).length,Email待發:email.filter(function(e){return String(e.通知狀態||'')==='queued'}).length,Email已發:email.filter(function(e){return String(e.通知狀態||'')==='已發送'}).length,檔案數:(detail.files||[]).length,財務筆數:(detail.finance||[]).length,結案筆數:(detail.closing||[]).length}}
function PODetail_timeline(data){var got=PODetail_get(data);if(!got.success)return got;var d=got.data.detail;var items=[];function push(type,row,date,title){items.push({type:type,date:date||row.建立時間||row.活動日期||'',title:title,raw:row})}push('專案',d.project,d.project.建立時間,'建立專案：'+(d.project.專案名稱||''));(d.events||[]).forEach(function(r){push('場次',r,r.活動日期,'場次：'+(r.活動名稱||''))});(d.registrations||[]).forEach(function(r){push('報名',r,r.建立時間,'報名：'+(r.姓名||''))});(d.tasks||[]).forEach(function(r){push('任務',r,r.截止日,'任務：'+(r.任務名稱||''))});(d.email||[]).forEach(function(r){push('Email',r,r.建立時間,'通知：'+(r.姓名||r.Email||''))});items.sort(function(a,b){return String(a.date).localeCompare(String(b.date))});return{success:true,message:'專案時間軸完成。',data:{total:items.length,items:items}}}
