/* ProjectOps ERP｜Registration Operation Runtime v1
 * 報名營運串連：錄取 → 名冊 → CRM → Email → 課前提醒入口
 */
function handleProjectOpsRegistrationRuntimeAction(action,data){data=data||{};try{if(action==='project.registration.finalize'||action==='專案報名結轉')return PORuntime_finalize(data);if(action==='project.registration.summary'||action==='專案報名摘要')return PORuntime_summary(data);if(action==='project.registration.notify'||action==='專案報名通知')return PORuntime_notify(data);return null;}catch(err){return{success:false,message:'報名營運 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POREG_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsRegistrationRuntimeAction(action,data);if(handled)return handled;return POREG_PREV_GATEWAY(action,data);};}
function POR_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POR_project(data){if(typeof PODetail_findProject==='function')return PODetail_findProject(data);var rows=POR_read('00_專案主檔');return rows.find(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')})||null}
function POR_match(row,project,data){if(!row||!project)return false;var pid=String(project.專案ID||'');var tid=String(project.標案ID||'');var cid=String(project.課程ID||'');if(String(row.專案ID||'')===pid)return true;if(tid&&String(row.標案ID||'')===tid)return true;if(cid&&String(row.課程ID||'')===cid)return true;if(data.場次ID&&String(row.場次ID||'')===String(data.場次ID))return true;if(data.招生ID&&String(row.招生ID||'')===String(data.招生ID))return true;return false}
function PORuntime_summary(data){var project=POR_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var regs=POR_read('86_報名資料').filter(function(r){return POR_match(r,project,data)});var out={專案ID:project.專案ID,專案名稱:project.專案名稱,total:regs.length,待審核:0,已錄取:0,候補:0,不錄取:0,有Email:0,已通知:0};regs.forEach(function(r){var s=String(r.錄取狀態||r.審核狀態||'待審核');if(s.indexOf('待')>=0)out.待審核++;if(s==='已錄取'||s==='通過')out.已錄取++;if(s==='候補')out.候補++;if(s==='不錄取'||s==='不通過')out.不錄取++;if(r.Email)out.有Email++;if(String(r.通知狀態||'').indexOf('已')>=0)out.已通知++;});return{success:true,message:'專案報名摘要完成。',data:out}}
function PORuntime_finalize(data){var project=POR_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var result={project:project,roster:null,crm:null,email:null,summary:null};if(typeof GovOpsReg_Roster_generate==='function')result.roster=GovOpsReg_Roster_generate(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID,課程ID:project.課程ID}));else if(typeof handleGovOpsRegistrationAction==='function')result.roster=handleGovOpsRegistrationAction('registration.roster.generate',Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID}));else result.roster={success:false,message:'名冊模組尚未載入'};
if(typeof GovOpsParticipantMaster_syncRoster==='function')result.crm=GovOpsParticipantMaster_syncRoster(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,標案ID:project.標案ID,課程ID:project.課程ID}));else result.crm={success:false,message:'CRM同步模組尚未載入'};
if(data.createEmail!==false)result.email=PORuntime_notify(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,通知類型:data.通知類型||'錄取通知'}));
result.summary=PORuntime_summary(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID})).data;return{success:true,message:'專案報名已完成結轉：名冊、CRM、通知已處理。',data:result}}
function PORuntime_notify(data){var project=POR_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var status=data.錄取狀態||'已錄取';var notice=data.通知類型||'錄取通知';var result=null;if(typeof GovOpsEmail_Admission_queueBatch==='function')result=GovOpsEmail_Admission_queueBatch(Object.assign({},data,{tenantId:project.tenantId,專案ID:project.專案ID,標案ID:project.標案ID,課程ID:project.課程ID,錄取狀態:status,通知類型:notice}));else result={success:false,message:'Email通知模組尚未載入'};return{success:true,message:'專案報名通知流程完成。',data:{project:project,email:result}}}
