/* ProjectOps ERP｜Task Operation Runtime v1
 * 任務營運串連：專案/場次 → 任務範本 → 派工 → 提醒
 */
function handleProjectOpsTaskRuntimeAction(action,data){data=data||{};try{if(action==='project.task.bootstrap'||action==='專案任務初始化')return POTask_bootstrap(data);if(action==='project.task.summary'||action==='專案任務摘要')return POTask_summary(data);if(action==='project.task.remind'||action==='專案任務提醒')return POTask_remind(data);return null;}catch(err){return{success:false,message:'任務營運 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POTASK_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsTaskRuntimeAction(action,data);if(handled)return handled;return POTASK_PREV_GATEWAY(action,data);};}
function POTask_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POTask_project(data){if(typeof PODetail_findProject==='function')return PODetail_findProject(data);return POTask_read('00_專案主檔').find(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')})||null}
function POTask_match(row,project,data){if(!row||!project)return false;if(String(row.專案ID||'')===String(project.專案ID||''))return true;if(project.標案ID&&String(row.標案ID||'')===String(project.標案ID))return true;if(project.課程ID&&String(row.課程ID||'')===String(project.課程ID))return true;if(data.場次ID&&String(row.場次ID||'')===String(data.場次ID))return true;return false}
function POTask_bootstrap(data){var project=POTask_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var eventId=data.場次ID||data.eventId||'';var templates=POTask_templates(project.案源類型);var created=[],skipped=[];templates.forEach(function(t){if(POTask_exists(project,eventId,t.name)){skipped.push(t.name);return;}var payload={tenantId:project.tenantId,專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID,課程ID:project.課程ID,場次ID:eventId,活動名稱:data.活動名稱||project.專案名稱,任務階段:t.stage,任務類型:t.type,任務名稱:t.name,任務內容:t.content,負責角色:t.role,截止日:data.截止日||'',任務狀態:'待指派'};var res=null;if(typeof GovOpsExecutionTask_create==='function')res=GovOpsExecutionTask_create(payload);else if(typeof handleGovOpsExecutionTaskAction==='function')res=handleGovOpsExecutionTaskAction('execution.task.create',payload);else{GovOpsProduct_ensureSheet('90_履約工作任務',['任務ID','tenantId','專案ID','案源類型','標案ID','課程ID','場次ID','活動名稱','任務階段','任務類型','任務名稱','任務內容','負責角色','負責人姓名','截止日','任務狀態','建立時間','更新時間']);payload.任務ID='TASK-'+Utilities.getUuid().slice(0,8);payload.建立時間=POTask_now();payload.更新時間=POTask_now();GovOpsProduct_append('90_履約工作任務',payload);res={success:true,message:'任務已建立',data:payload};}created.push(res);});return{success:true,message:'專案任務初始化完成。',data:{project:project,created:created.length,skipped:skipped,rows:created}}}
function POTask_summary(data){var project=POTask_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var rows=POTask_read('90_履約工作任務').filter(function(r){return POTask_match(r,project,data)});var out={total:rows.length,待指派:0,待處理:0,執行中:0,待確認:0,已完成:0,逾期:0,取消:0};rows.forEach(function(r){var s=String(r.任務狀態||'待指派');out[s]=(out[s]||0)+1;});return{success:true,message:'專案任務摘要完成。',data:out}}
function POTask_remind(data){var project=POTask_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var rows=POTask_read('90_履約工作任務').filter(function(r){return POTask_match(r,project,data)&&['待指派','待處理','執行中','逾期'].indexOf(String(r.任務狀態||''))>=0});var queued=[];rows.forEach(function(t){if(typeof GovOpsNotify_Queue_create==='function'){queued.push(GovOpsNotify_Queue_create({tenantId:project.tenantId,來源模組:'project.task',來源ID:t.任務ID,通知類型:'任務提醒',通知渠道:'系統/Email',收件人:t.負責人Email||'',收件人姓名:t.負責人姓名||t.負責角色||'',標題:'任務提醒｜'+(t.任務名稱||''),內容:'請處理專案「'+(project.專案名稱||'')+'」任務：'+(t.任務名稱||''),優先級:30,userId:data.userId||''}));}});return{success:true,message:'專案任務提醒已建立。',data:{total:rows.length,queued:queued.length,rows:queued}}}
function POTask_templates(sourceType){var base=[{stage:'課前',type:'人員',name:'確認講師與工作人員',role:'project_manager',content:'確認講師、助教、工作人員是否完成指派。'},{stage:'課前',type:'招生',name:'確認招生頁與報名表',role:'admin_staff',content:'確認招生設定、報名連結、名額與審核規則。'},{stage:'課前',type:'通知',name:'寄送錄取與課前通知',role:'admin_staff',content:'確認錄取通知、候補通知與開課前提醒。'},{stage:'課前',type:'場地',name:'確認場地設備與教材',role:'staff',content:'確認場地、設備、教材、簽到表與物品。'},{stage:'當日',type:'執行',name:'報到簽到與現場紀錄',role:'staff',content:'完成報到、簽到、現場照片與突發狀況紀錄。'},{stage:'課後',type:'成果',name:'上傳成果照片與簽到表',role:'admin_staff',content:'上傳照片、簽到表、成果資料到檔案中心。'},{stage:'課後',type:'滿意度',name:'彙整滿意度與回饋',role:'admin_staff',content:'彙整紙本或線上滿意度，產生統計與建議。'},{stage:'核銷',type:'財務',name:'整理支出與核銷憑證',role:'finance',content:'整理講師費、場地費、餐費、材料費、收據與發票。'},{stage:'結案',type:'結案',name:'完成結案資料與交付包',role:'project_manager',content:'確認成果、附件、核銷、檢討建議與結案報告。'}];if(sourceType==='政府標案')base.unshift({stage:'投標/契約',type:'標案',name:'確認契約與驗收條件',role:'project_manager',content:'確認契約、履約期間、驗收條件、押標金與履約保證金。'});if(sourceType==='自辦課程')base.unshift({stage:'課前',type:'營收',name:'確認開課人數與收款狀態',role:'finance',content:'確認最低開課人數、報名費收入、未收款與退費規則。'});return base}
function POTask_exists(project,eventId,name){return POTask_read('90_履約工作任務').some(function(r){return String(r.tenantId||'')===String(project.tenantId)&&String(r.專案ID||'')===String(project.專案ID)&&String(r.場次ID||'')===String(eventId||'')&&String(r.任務名稱||'')===String(name)})}
function POTask_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
