/* ProjectOps ERP｜Finance Operation Runtime v1
 * 財務營運串連：專案/場次 → 應收 → 收款 → 支出 → 核銷
 */
function handleProjectOpsFinanceRuntimeAction(action,data){data=data||{};try{if(action==='project.finance.receivable.create'||action==='專案建立應收')return POFin_receivableCreate(data);if(action==='project.finance.income.record'||action==='專案收款紀錄')return POFin_incomeRecord(data);if(action==='project.finance.expense.record'||action==='專案支出紀錄')return POFin_expenseRecord(data);if(action==='project.finance.reimburse.record'||action==='專案核銷紀錄')return POFin_reimburseRecord(data);if(action==='project.finance.summary'||action==='專案財務摘要')return POFin_summary(data);return null;}catch(err){return{success:false,message:'財務營運 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POFIN_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsFinanceRuntimeAction(action,data);if(handled)return handled;return POFIN_PREV_GATEWAY(action,data);};}
function POFin_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function POFin_ensure(){GovOpsProduct_ensureSheet('200_專案應收款',['應收ID','tenantId','專案ID','案源類型','標案ID','課程ID','場次ID','對象','項目','金額','預計收款日','收款狀態','已收金額','未收金額','建立時間','更新時間','備註']);GovOpsProduct_ensureSheet('201_專案收款紀錄',['收款ID','tenantId','專案ID','案源類型','標案ID','課程ID','場次ID','應收ID','對象','項目','金額','收款日期','收款方式','建立時間','備註']);GovOpsProduct_ensureSheet('202_專案支出紀錄',['支出ID','tenantId','專案ID','案源類型','標案ID','課程ID','場次ID','支出類型','對象','項目','金額','支出日期','付款狀態','憑證URL','建立時間','備註']);GovOpsProduct_ensureSheet('203_專案核銷紀錄',['核銷ID','tenantId','專案ID','案源類型','標案ID','課程ID','場次ID','核銷類型','金額','憑證URL','核銷狀態','建立時間','更新時間','備註']);}
function POFin_project(data){if(typeof PODetail_findProject==='function')return PODetail_findProject(data);try{return GovOpsProduct_readRows('00_專案主檔').find(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')})||null}catch(e){return null}}
function POFin_base(data,project){return{tenantId:project.tenantId,專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID||'',課程ID:project.課程ID||'',場次ID:data.場次ID||data.eventId||''}}
function POFin_receivableCreate(data){POFin_ensure();var project=POFin_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var amount=Number(data.金額||data.amount||0);var row=Object.assign(POFin_base(data,project),{應收ID:'AR-'+Utilities.getUuid().slice(0,8),對象:data.對象||data.customer||project.主辦單位||'',項目:data.項目||data.item||'專案收入',金額:amount,預計收款日:data.預計收款日||data.dueDate||'',收款狀態:'未收款',已收金額:0,未收金額:amount,建立時間:POFin_now(),更新時間:POFin_now(),備註:data.備註||''});GovOpsProduct_append('200_專案應收款',row);return{success:true,message:'專案應收款已建立。',data:row}}
function POFin_incomeRecord(data){POFin_ensure();var project=POFin_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var amount=Number(data.金額||data.amount||0);var row=Object.assign(POFin_base(data,project),{收款ID:'IN-'+Utilities.getUuid().slice(0,8),應收ID:data.應收ID||'',對象:data.對象||data.customer||'',項目:data.項目||data.item||'收款',金額:amount,收款日期:data.收款日期||data.date||POFin_now(),收款方式:data.收款方式||data.method||'',建立時間:POFin_now(),備註:data.備註||''});GovOpsProduct_append('201_專案收款紀錄',row);POFin_updateReceivable(row);return{success:true,message:'專案收款已記錄。',data:row}}
function POFin_expenseRecord(data){POFin_ensure();var project=POFin_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var row=Object.assign(POFin_base(data,project),{支出ID:'EX-'+Utilities.getUuid().slice(0,8),支出類型:data.支出類型||data.expenseType||'一般支出',對象:data.對象||'',項目:data.項目||data.item||'',金額:Number(data.金額||data.amount||0),支出日期:data.支出日期||data.date||POFin_now(),付款狀態:data.付款狀態||'已付款',憑證URL:data.憑證URL||data.receiptUrl||'',建立時間:POFin_now(),備註:data.備註||''});GovOpsProduct_append('202_專案支出紀錄',row);return{success:true,message:'專案支出已記錄。',data:row}}
function POFin_reimburseRecord(data){POFin_ensure();var project=POFin_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};var row=Object.assign(POFin_base(data,project),{核銷ID:'RB-'+Utilities.getUuid().slice(0,8),核銷類型:data.核銷類型||'一般核銷',金額:Number(data.金額||data.amount||0),憑證URL:data.憑證URL||data.receiptUrl||'',核銷狀態:data.核銷狀態||'待核銷',建立時間:POFin_now(),更新時間:POFin_now(),備註:data.備註||''});GovOpsProduct_append('203_專案核銷紀錄',row);return{success:true,message:'專案核銷紀錄已建立。',data:row}}
function POFin_summary(data){POFin_ensure();var project=POFin_project(data);if(!project)return{success:false,message:'找不到專案。',data:{}};function rows(sheet){return GovOpsProduct_readRows(sheet).filter(function(r){return String(r.tenantId||'')===String(project.tenantId)&&String(r.專案ID||'')===String(project.專案ID)})}var ar=rows('200_專案應收款'),inc=rows('201_專案收款紀錄'),exp=rows('202_專案支出紀錄'),rb=rows('203_專案核銷紀錄');function sum(list,key){return list.reduce(function(a,r){return a+Number(r[key]||0)},0)}var out={專案ID:project.專案ID,專案名稱:project.專案名稱,應收總額:sum(ar,'金額'),已收總額:sum(inc,'金額'),未收總額:sum(ar,'未收金額'),支出總額:sum(exp,'金額'),核銷總額:sum(rb,'金額'),毛利:sum(inc,'金額')-sum(exp,'金額'),應收筆數:ar.length,收款筆數:inc.length,支出筆數:exp.length,核銷筆數:rb.length};return{success:true,message:'專案財務摘要完成。',data:out}}
function POFin_updateReceivable(income){try{if(!income.應收ID)return;var rows=GovOpsProduct_readRows('200_專案應收款');var ar=rows.find(function(r){return String(r.應收ID||'')===String(income.應收ID)});if(!ar)return;var paid=Number(ar.已收金額||0)+Number(income.金額||0);var total=Number(ar.金額||0);var unpaid=Math.max(total-paid,0);GovOpsProduct_update('200_專案應收款',ar._row,{已收金額:paid,未收金額:unpaid,收款狀態:unpaid<=0?'已收款':'部分收款',更新時間:POFin_now()});}catch(e){}}
