/* ProjectOps ERP｜Closing Operation Runtime v1
 * 結案營運串連：成果 → 出席 → 滿意度 → 附件 → 核銷 → 缺件檢查 → 結案摘要
 */
function handleProjectOpsClosingRuntimeAction(action,data){data=data||{};try{if(action==='project.closing.check'||action==='專案結案檢查')return POClosing_check(data);if(action==='project.closing.summary'||action==='專案結案摘要')return POClosing_summary(data);if(action==='project.closing.create'||action==='建立專案結案')return POClosing_create(data);if(action==='project.closing.package'||action==='專案交付包')return POClosing_package(data);return null;}catch(err){return{success:false,message:'結案營運 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POCLOSE_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsClosingRuntimeAction(action,data);if(handled)return handled;return POCLOSE_PREV_GATEWAY(action,data);};}
function POClose_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function POClose_ensure(){GovOpsProduct_ensureSheet('210_專案結案主檔',['結案ID','tenantId','專案ID','案源類型','專案名稱','結案狀態','出席率','滿意度平均','成果附件數','核銷附件數','缺件數','檢討建議','建立時間','更新時間','備註']);GovOpsProduct_ensureSheet('211_專案缺件檢查',['檢查ID','tenantId','專案ID','項目','狀態','說明','建立時間']);GovOpsProduct_ensureSheet('212_專案交付包',['交付包ID','tenantId','專案ID','交付項目','檔案URL','狀態','建立時間','備註']);}
function POClose_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POClose_project(data){if(typeof PODetail_findProject==='function')return PODetail_findProject(data);return POClose_read('00_專案主檔').find(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')})||null}
function POClose_match(row,project){if(!row||!project)return false;if(String(row.專案ID||'')===String(project.專案ID||''))return true;if(project.標案ID&&String(row.標案ID||'')===String(project.標案ID))return true;if(project.課程ID&&String(row.課程ID||'')===String(project.課程ID))return true;return false}
function POClosing_summary(data){POClose_ensure();var p=POClose_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var roster=POClose_read('88_學員名冊').filter(function(r){return POClose_match(r,p)});var files=POClose_read('96_檔案中心').filter(function(r){return POClose_match(r,p)});var reimburse=POClose_read('203_專案核銷紀錄').filter(function(r){return POClose_match(r,p)});var reg=POClose_read('86_報名資料').filter(function(r){return POClose_match(r,p)});var attend=roster.filter(function(r){return String(r.出席狀態||r.報到狀態||'').indexOf('已')>=0}).length;var attendBase=roster.length||reg.length||0;var attendanceRate=attendBase?Math.round(attend/attendBase*10000)/100:0;var satisfactionRows=POClose_read('滿意度統計').filter(function(r){return POClose_match(r,p)});var satAvg=0;if(satisfactionRows.length){satAvg=satisfactionRows.reduce(function(a,r){return a+Number(r.滿意度平均||r.平均分數||0)},0)/satisfactionRows.length;}var out={專案ID:p.專案ID,專案名稱:p.專案名稱,案源類型:p.案源類型,報名數:reg.length,名冊數:roster.length,實際出席:attend,出席率:attendanceRate,滿意度平均:Math.round(satAvg*100)/100,成果附件數:files.filter(function(f){return String(f.檔案類別||'').indexOf('成果')>=0||String(f.是否納入結案||'')==='是'}).length,核銷附件數:reimburse.length,檔案總數:files.length};return{success:true,message:'專案結案摘要完成。',data:out}}
function POClosing_check(data){POClose_ensure();var p=POClose_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var s=POClosing_summary(data).data;var checks=[];function add(item,ok,desc){checks.push({項目:item,狀態:ok?'完成':'缺件',說明:desc||''});}
add('學員名冊',s.名冊數>0,'需有名冊或錄取資料');add('出席統計',s.出席率>0,'需有實際出席或報到紀錄');add('成果附件',s.成果附件數>0,'需上傳成果照片或可納入結案附件');add('核銷資料',s.核銷附件數>0||p.案源類型==='自辦課程','政府標案通常需要核銷資料，自辦課程可視情況');add('滿意度',s.滿意度平均>0,'需紙本或線上滿意度統計');var missing=checks.filter(function(c){return c.狀態==='缺件'});checks.forEach(function(c){GovOpsProduct_append('211_專案缺件檢查',{檢查ID:'CHK-'+Utilities.getUuid().slice(0,8),tenantId:p.tenantId,專案ID:p.專案ID,項目:c.項目,狀態:c.狀態,說明:c.說明,建立時間:POClose_now()});});return{success:true,message:'專案結案檢查完成。',data:{summary:s,missing:missing.length,checks:checks}}}
function POClosing_create(data){POClose_ensure();var p=POClose_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var check=POClosing_check(data).data;var s=check.summary;var row={結案ID:'CLOSE-'+Utilities.getUuid().slice(0,8),tenantId:p.tenantId,專案ID:p.專案ID,案源類型:p.案源類型,專案名稱:p.專案名稱,結案狀態:check.missing>0?'待補件':'可結案',出席率:s.出席率,滿意度平均:s.滿意度平均,成果附件數:s.成果附件數,核銷附件數:s.核銷附件數,缺件數:check.missing,檢討建議:data.檢討建議||data.review||'',建立時間:POClose_now(),更新時間:POClose_now(),備註:data.備註||''};GovOpsProduct_append('210_專案結案主檔',row);return{success:true,message:'專案結案主檔已建立。',data:{closing:row,check:check}}}
function POClosing_package(data){POClose_ensure();var p=POClose_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var files=POClose_read('96_檔案中心').filter(function(r){return POClose_match(r,p)});var items=[];files.forEach(function(f){var include=String(f.是否納入結案||'')==='是'||String(f.是否納入核銷||'')==='是';if(include){var row={交付包ID:'PKG-'+Utilities.getUuid().slice(0,8),tenantId:p.tenantId,專案ID:p.專案ID,交付項目:f.檔案類別||f.文件類型||'附件',檔案URL:f.DriveURL||f.檔案URL||'',狀態:'已納入',建立時間:POClose_now(),備註:f.檔案名稱||f.標準檔名||''};GovOpsProduct_append('212_專案交付包',row);items.push(row);}});return{success:true,message:'專案交付包已建立。',data:{total:items.length,items:items}}}
