/* ProjectOps ERP｜Unified Runtime v1
 * 統一營運 Runtime：Dashboard、全域搜尋、健康檢查，納入專案/財務/結案資料。
 */
function handleProjectOpsUnifiedRuntimeAction(action,data){data=data||{};try{if(action==='projectops.dashboard.summary'||action==='ProjectOps營運總覽')return POU_dashboard(data);if(action==='projectops.search'||action==='ProjectOps全域搜尋')return POU_search(data);if(action==='projectops.health'||action==='ProjectOps健康檢查')return POU_health(data);return null;}catch(err){return{success:false,message:'ProjectOps Unified Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POU_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsUnifiedRuntimeAction(action,data);if(handled)return handled;return POU_PREV_GATEWAY(action,data);};}
function POU_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POU_tenant(row,tenantId){return !row.tenantId||String(row.tenantId)===String(tenantId)}
function POU_dashboard(data){var tenantId=data.tenantId||'TENANT-DEMO';function rows(sheet){return POU_read(sheet).filter(function(r){return POU_tenant(r,tenantId)})}var projects=rows('00_專案主檔'),regs=rows('86_報名資料'),participants=rows('96_學員資料庫'),tasks=rows('90_履約工作任務'),ar=rows('200_專案應收款'),income=rows('201_專案收款紀錄'),expense=rows('202_專案支出紀錄'),closing=rows('210_專案結案主檔');function sum(list,key){return list.reduce(function(a,r){return a+Number(r[key]||0)},0)}var out={projects:projects.length,政府標案:projects.filter(function(p){return p.案源類型==='政府標案'}).length,自辦課程:projects.filter(function(p){return p.案源類型==='自辦課程'}).length,合作課程:projects.filter(function(p){return p.案源類型==='合作課程'}).length,registrations:regs.length,待審核:regs.filter(function(r){return String(r.錄取狀態||r.審核狀態||'').indexOf('待')>=0}).length,已錄取:regs.filter(function(r){return String(r.錄取狀態||'')==='已錄取'}).length,participants:participants.length,tasks:tasks.length,未完成任務:tasks.filter(function(t){return['待指派','待處理','執行中','逾期'].indexOf(String(t.任務狀態||''))>=0}).length,逾期任務:tasks.filter(function(t){return String(t.任務狀態||'')==='逾期'}).length,應收總額:sum(ar,'金額'),已收總額:sum(income,'金額'),未收總額:sum(ar,'未收金額'),支出總額:sum(expense,'金額'),結案件數:closing.length,待補件:closing.filter(function(c){return String(c.結案狀態||'')==='待補件'}).length,可結案:closing.filter(function(c){return String(c.結案狀態||'')==='可結案'}).length};return{success:true,message:'ProjectOps營運總覽完成。',data:out}}
function POU_search(data){var tenantId=data.tenantId||'TENANT-DEMO';var kw=String(data.keyword||data.關鍵字||'').trim();if(!kw)return{success:false,message:'請輸入搜尋關鍵字。',data:{}};var sources=[['專案','00_專案主檔',['專案ID','案源類型','專案名稱','專案狀態','主辦單位']],['政府標案','01_標案池',['標案ID','標案名稱','機關名稱','標案狀態']],['自辦課程','06_自辦課程主檔',['課程ID','專案ID','課程名稱','課程定價']],['場次','74_履約活動場次',['專案ID','場次ID','活動名稱','活動日期','地點']],['報名','86_報名資料',['報名ID','姓名','電話','Email','錄取狀態']],['名冊','88_學員名冊',['姓名','Email','活動名稱','出席狀態']],['學員','96_學員資料庫',['學員ID','姓名','電話','Email','CRM狀態']],['任務','90_履約工作任務',['任務ID','任務名稱','負責人姓名','任務狀態']],['財務應收','200_專案應收款',['專案ID','對象','項目','金額','收款狀態']],['收款','201_專案收款紀錄',['專案ID','對象','項目','金額','收款日期']],['支出','202_專案支出紀錄',['專案ID','支出類型','項目','金額']],['結案','210_專案結案主檔',['專案ID','專案名稱','結案狀態','缺件數']]];var results=[];sources.forEach(function(s){POU_read(s[1]).filter(function(r){return POU_tenant(r,tenantId)&&JSON.stringify(r).indexOf(kw)>=0}).slice(0,50).forEach(function(r){var item={source:s[0],sheet:s[1],summary:{}};s[2].forEach(function(k){item.summary[k]=r[k]||''});item.raw=r;results.push(item);});});return{success:true,message:'ProjectOps全域搜尋完成。',data:{keyword:kw,total:results.length,results:results.slice(0,300)}}}
function POU_health(data){var sheets=['00_專案主檔','01_標案池','06_自辦課程主檔','74_履約活動場次','85_招生設定','86_報名資料','88_學員名冊','96_學員資料庫','90_履約工作任務','103_Email通知佇列','200_專案應收款','201_專案收款紀錄','202_專案支出紀錄','203_專案核銷紀錄','210_專案結案主檔','211_專案缺件檢查','212_專案交付包'];var checks=sheets.map(function(s){var r=POU_read(s);return{sheet:s,status:'OK',rows:r.length,message:'可讀取'}});var ok=checks.filter(function(c){return c.status==='OK'}).length;return{success:true,message:'ProjectOps健康檢查完成。',data:{total:checks.length,ok:ok,warn:checks.length-ok,checks:checks}}}
