/* ProjectOps ERP｜Document Runtime v1
 * 結案文件輸出 Runtime：組裝結案報告資料，輸出文字版與HTML版。
 */
function handleProjectOpsDocumentRuntimeAction(action,data){data=data||{};try{if(action==='project.document.closingReport'||action==='專案結案報告')return PODoc_closingReport(data);if(action==='project.document.deliveryHtml'||action==='專案交付HTML')return PODoc_deliveryHtml(data);return null;}catch(err){return{success:false,message:'文件輸出 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var PODOC_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsDocumentRuntimeAction(action,data);if(handled)return handled;return PODOC_PREV_GATEWAY(action,data);};}
function PODoc_project(data){if(typeof POClose_project==='function')return POClose_project(data);if(typeof PODetail_findProject==='function')return PODetail_findProject(data);return null}
function PODoc_summary(data){if(typeof POClosing_summary==='function'){var r=POClosing_summary(data);return r.success?r.data:{}}return{}}
function PODoc_finance(data){if(typeof POFin_summary==='function'){var r=POFin_summary(data);return r.success?r.data:{}}return{}}
function PODoc_detail(data){if(typeof PODetail_get==='function'){var r=PODetail_get(data);return r.success?r.data.detail:{}}return{}}
function PODoc_closingReport(data){var p=PODoc_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var s=PODoc_summary(data),f=PODoc_finance(data),d=PODoc_detail(data);var lines=[];lines.push('# '+(p.專案名稱||'專案結案報告'));lines.push('');lines.push('## 一、專案基本資料');lines.push('專案ID：'+(p.專案ID||''));lines.push('案源類型：'+(p.案源類型||''));lines.push('主辦單位：'+(p.主辦單位||''));lines.push('合作單位：'+(p.合作單位||''));lines.push('執行期間：'+(p.開始日期||'')+' ～ '+(p.結束日期||''));lines.push('');lines.push('## 二、執行成果摘要');lines.push('報名人數：'+(s.報名數||0));lines.push('名冊人數：'+(s.名冊數||0));lines.push('實際出席：'+(s.實際出席||0));lines.push('出席率：'+(s.出席率||0)+'%');lines.push('滿意度平均：'+(s.滿意度平均||0));lines.push('成果附件數：'+(s.成果附件數||0));lines.push('核銷附件數：'+(s.核銷附件數||0));lines.push('');lines.push('## 三、財務摘要');lines.push('應收總額：'+(f.應收總額||0));lines.push('已收總額：'+(f.已收總額||0));lines.push('未收總額：'+(f.未收總額||0));lines.push('支出總額：'+(f.支出總額||0));lines.push('毛利：'+(f.毛利||0));lines.push('');lines.push('## 四、任務執行');var tasks=(d.tasks||[]);if(tasks.length){tasks.forEach(function(t,i){lines.push((i+1)+'. '+(t.任務名稱||'')+'｜'+(t.任務狀態||''));});}else{lines.push('尚無任務資料。')}lines.push('');lines.push('## 五、檢討與建議');lines.push(data.檢討建議||data.review||'待補。');lines.push('');lines.push('## 六、附件清單');var files=(d.files||[]);if(files.length){files.forEach(function(file,i){lines.push((i+1)+'. '+(file.檔案類別||file.文件類型||'附件')+'｜'+(file.標準檔名||file.檔案名稱||'')+'｜'+(file.DriveURL||file.檔案URL||''));});}else{lines.push('尚無附件資料。')}return{success:true,message:'專案結案報告已組裝完成。',data:{project:p,markdown:lines.join('\n'),summary:s,finance:f}}}
function PODoc_deliveryHtml(data){var r=PODoc_closingReport(data);if(!r.success)return r;var html='<!DOCTYPE html><html><head><meta charset="UTF-8"><title>'+PODoc_escape(r.data.project.專案名稱||'結案報告')+'</title><style>body{font-family:Arial,"Microsoft JhengHei",sans-serif;line-height:1.8;padding:32px;color:#172033}h1{color:#102542}h2{border-bottom:1px solid #ddd;padding-bottom:6px}pre{white-space:pre-wrap;background:#f8fafc;padding:16px;border-radius:12px}</style></head><body><pre>'+PODoc_escape(r.data.markdown)+'</pre></body></html>';return{success:true,message:'專案交付HTML已產生。',data:{html:html,markdown:r.data.markdown}}}
function PODoc_escape(s){return String(s||'').replace(/[<>&]/g,function(c){return{'<':'&lt;','>':'&gt;','&':'&amp;'}[c]})}
