/* ProjectOps ERP｜Meal Preference Runtime v1
 * 用餐習慣統計：報名/名冊 → 餐點統計 → 餐飲廠商備註 → 結案/核銷參考
 */
function handleProjectOpsMealRuntimeAction(action,data){data=data||{};try{if(action==='project.meal.summary'||action==='專案用餐統計')return POMeal_summary(data);if(action==='project.meal.list'||action==='專案用餐名單')return POMeal_list(data);if(action==='project.meal.vendorNote'||action==='餐飲廠商備註')return POMeal_vendorNote(data);return null;}catch(err){return{success:false,message:'用餐統計 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POMEAL_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsMealRuntimeAction(action,data);if(handled)return handled;return POMEAL_PREV_GATEWAY(action,data);};}
function POMeal_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POMeal_project(data){if(typeof PODetail_findProject==='function')return PODetail_findProject(data);return POMeal_read('00_專案主檔').find(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')})||null}
function POMeal_match(row,project,data){if(!row||!project)return false;if(String(row.專案ID||'')===String(project.專案ID||''))return true;if(project.標案ID&&String(row.標案ID||'')===String(project.標案ID))return true;if(project.課程ID&&String(row.課程ID||'')===String(project.課程ID))return true;if(data.場次ID&&String(row.場次ID||'')===String(data.場次ID))return true;if(data.招生ID&&String(row.招生ID||'')===String(data.招生ID))return true;return false}
function POMeal_sourceRows(data){var p=POMeal_project(data);if(!p)return{project:null,rows:[]};var roster=POMeal_read('88_學員名冊').filter(function(r){return POMeal_match(r,p,data)});var regs=POMeal_read('86_報名資料').filter(function(r){return POMeal_match(r,p,data)});var rows=roster.length?roster:regs;return{project:p,rows:rows}}
function POMeal_summary(data){var src=POMeal_sourceRows(data);if(!src.project)return{success:false,message:'找不到專案。',data:{}};var out={專案ID:src.project.專案ID,專案名稱:src.project.專案名稱,總人數:src.rows.length,需要用餐:0,不用餐:0,葷食:0,素食:0,不吃牛:0,不吃豬:0,特殊飲食:0,過敏需求:0,未填寫:0,備註清單:[]};src.rows.forEach(function(r){var text=JSON.stringify(r);var meal=String(r.是否用餐||r.用餐||r.餐點需求||'').trim();var pref=String(r.用餐習慣||r.飲食習慣||r.餐點類型||r.餐別||'').trim();var allergy=String(r.過敏食材||r.食物過敏||'').trim();var note=String(r.用餐備註||r.餐點備註||r.備註||'').trim();if(!meal&&!pref)out.未填寫++;if(meal.indexOf('不')>=0||pref.indexOf('不用')>=0)out.不用餐++;else out.需要用餐++;if(pref.indexOf('素')>=0||text.indexOf('素食')>=0)out.素食++;else if(pref||meal)out.葷食++;if(text.indexOf('不吃牛')>=0||text.indexOf('不食牛')>=0)out.不吃牛++;if(text.indexOf('不吃豬')>=0||text.indexOf('不食豬')>=0)out.不吃豬++;if(pref.indexOf('特殊')>=0||note.indexOf('特殊')>=0)out.特殊飲食++;if(allergy)out.過敏需求++;if(note||allergy)out.備註清單.push({姓名:r.姓名||'',用餐習慣:pref,過敏食材:allergy,備註:note});});return{success:true,message:'專案用餐統計完成。',data:out}}
function POMeal_list(data){var src=POMeal_sourceRows(data);if(!src.project)return{success:false,message:'找不到專案。',data:{}};var rows=src.rows.map(function(r){return{姓名:r.姓名||'',電話:r.電話||'',Email:r.Email||'',是否用餐:r.是否用餐||r.用餐||'',用餐習慣:r.用餐習慣||r.飲食習慣||r.餐點類型||'',過敏食材:r.過敏食材||r.食物過敏||'',備註:r.用餐備註||r.餐點備註||r.備註||''};});return{success:true,message:'專案用餐名單完成。',data:{total:rows.length,rows:rows}}}
function POMeal_vendorNote(data){var s=POMeal_summary(data);if(!s.success)return s;var d=s.data;var lines=[];lines.push('餐點統計｜'+(d.專案名稱||''));lines.push('總人數：'+d.總人數);lines.push('需要用餐：'+d.需要用餐);lines.push('不用餐：'+d.不用餐);lines.push('葷食：約 '+d.葷食);lines.push('素食：約 '+d.素食);lines.push('不吃牛：'+d.不吃牛);lines.push('不吃豬：'+d.不吃豬);lines.push('特殊飲食：'+d.特殊飲食);lines.push('過敏需求：'+d.過敏需求);if(d.備註清單.length){lines.push('');lines.push('特殊備註：');d.備註清單.forEach(function(x,i){lines.push((i+1)+'. '+(x.姓名||'')+'｜'+(x.用餐習慣||'')+'｜過敏：'+(x.過敏食材||'無')+'｜'+(x.備註||''));});}return{success:true,message:'餐飲廠商備註已產生。',data:{note:lines.join('\n'),summary:d}}}
