/* ProjectOps ERP｜Auto Accounting Runtime v1
 * 人話記帳 → 自動判斷會計科目、借貸方向、報稅分類、應收應付。
 */
function handleProjectOpsAutoAccountingAction(action,data){data=data||{};try{if(action==='project.accounting.autoClassify'||action==='自動會計判斷')return POAcct_autoClassify(data);if(action==='project.accounting.autoPostIncome'||action==='自動收入入帳')return POAcct_autoPostIncome(data);if(action==='project.accounting.autoPostExpense'||action==='自動支出入帳')return POAcct_autoPostExpense(data);if(action==='project.accounting.autoPostReceivable'||action==='自動應收入帳')return POAcct_autoPostReceivable(data);if(action==='project.accounting.autoPostPayable'||action==='自動應付入帳')return POAcct_autoPostPayable(data);if(action==='project.accounting.projectPL'||action==='專案損益')return POAcct_projectPL(data);return null;}catch(err){return{success:false,message:'自動會計 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POACCT_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsAutoAccountingAction(action,data);if(handled)return handled;return POACCT_PREV_GATEWAY(action,data);};}
function POAcct_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function POAcct_ensure(){GovOpsProduct_ensureSheet('220_會計科目主檔',['科目代碼','科目名稱','科目類型','報稅分類','啟用狀態','建立時間']);GovOpsProduct_ensureSheet('221_會計分錄',['分錄ID','tenantId','專案ID','案源類型','場次ID','交易類型','描述','借方科目','貸方科目','金額','交易日期','年度','憑證URL','是否可報稅','建立時間','備註']);POAcct_seedAccounts();}
function POAcct_seedAccounts(){try{var rows=GovOpsProduct_readRows('220_會計科目主檔');if(rows.length)return;['現金|資產|現金','銀行存款|資產|銀行','應收帳款|資產|應收','應付帳款|負債|應付','預收收入|負債|預收','政府標案收入|收入|收入','課程收入|收入|收入','企業委託收入|收入|收入','其他收入|收入|收入','講師費|費用|可列支','工作人員費|費用|可列支','場地費|費用|可列支','餐費|費用|可列支','材料費|費用|可列支','交通費|費用|可列支','印刷費|費用|可列支','行政雜支|費用|可列支','平台服務費|費用|可列支','其他支出|費用|可列支'].forEach(function(x,i){var p=x.split('|');GovOpsProduct_append('220_會計科目主檔',{科目代碼:'ACCT-'+('000'+(i+1)).slice(-3),科目名稱:p[0],科目類型:p[1],報稅分類:p[2],啟用狀態:'啟用',建立時間:POAcct_now()});});}catch(e){}}
function POAcct_autoClassify(data){POAcct_ensure();var text=String(data.description||data.描述||data.項目||'');var amount=Number(data.amount||data.金額||0);var method=String(data.method||data.付款方式||data.收款方式||'');var projectType=String(data.案源類型||'');var type=String(data.transactionType||data.交易類型||'');if(!type){if(text.indexOf('未收')>=0||text.indexOf('還沒收到')>=0)type='應收';else if(text.indexOf('未付')>=0||text.indexOf('還沒付')>=0||text.indexOf('待支付')>=0)type='應付';else if(text.indexOf('收到')>=0||text.indexOf('收款')>=0||text.indexOf('收入')>=0||text.indexOf('報名費')>=0)type='收入';else if(text.indexOf('支付')>=0||text.indexOf('支出')>=0||text.indexOf('費')>=0)type='支出';else type='待判斷';}
var cashAcct=(method.indexOf('現金')>=0)?'現金':'銀行存款';var incomeAcct='其他收入';if(projectType==='政府標案'||text.indexOf('政府')>=0||text.indexOf('標案')>=0)incomeAcct='政府標案收入';else if(projectType==='自辦課程'||text.indexOf('課程')>=0||text.indexOf('報名費')>=0)incomeAcct='課程收入';else if(text.indexOf('企業')>=0||text.indexOf('委託')>=0)incomeAcct='企業委託收入';
var expenseAcct='其他支出';if(text.indexOf('講師')>=0)expenseAcct='講師費';else if(text.indexOf('工作人員')>=0||text.indexOf('助教')>=0)expenseAcct='工作人員費';else if(text.indexOf('場地')>=0)expenseAcct='場地費';else if(text.indexOf('餐')>=0||text.indexOf('便當')>=0||text.indexOf('用餐')>=0)expenseAcct='餐費';else if(text.indexOf('材料')>=0)expenseAcct='材料費';else if(text.indexOf('交通')>=0||text.indexOf('車資')>=0)expenseAcct='交通費';else if(text.indexOf('印刷')>=0)expenseAcct='印刷費';else if(text.indexOf('行政')>=0)expenseAcct='行政雜支';
var debit='',credit='',tax='是';if(type==='收入'){debit=cashAcct;credit=incomeAcct;}else if(type==='應收'){debit='應收帳款';credit=incomeAcct;}else if(type==='支出'){debit=expenseAcct;credit=cashAcct;}else if(type==='應付'){debit=expenseAcct;credit='應付帳款';}else{tax='待判斷';}
return{success:true,message:'自動會計判斷完成。',data:{交易類型:type,金額:amount,借方科目:debit,貸方科目:credit,收入科目:incomeAcct,支出科目:expenseAcct,資金科目:cashAcct,是否可報稅:tax,年度:POAcct_year(data.date||data.日期||POAcct_now())}}}
function POAcct_createEntry(data,cls){POAcct_ensure();var c=cls||POAcct_autoClassify(data).data;var row={分錄ID:'JE-'+Utilities.getUuid().slice(0,8),tenantId:data.tenantId||'TENANT-DEMO',專案ID:data.專案ID||data.projectId||'',案源類型:data.案源類型||'',場次ID:data.場次ID||'',交易類型:c.交易類型,描述:data.description||data.描述||data.項目||'',借方科目:c.借方科目,貸方科目:c.貸方科目,金額:Number(data.amount||data.金額||0),交易日期:data.date||data.日期||POAcct_now(),年度:c.年度,憑證URL:data.憑證URL||data.receiptUrl||'',是否可報稅:c.是否可報稅,建立時間:POAcct_now(),備註:data.備註||''};GovOpsProduct_append('221_會計分錄',row);return{success:true,message:'會計分錄已建立。',data:row}}
function POAcct_autoPostIncome(data){data.交易類型='收入';return POAcct_createEntry(data)}
function POAcct_autoPostExpense(data){data.交易類型='支出';return POAcct_createEntry(data)}
function POAcct_autoPostReceivable(data){data.交易類型='應收';return POAcct_createEntry(data)}
function POAcct_autoPostPayable(data){data.交易類型='應付';return POAcct_createEntry(data)}
function POAcct_projectPL(data){POAcct_ensure();var rows=GovOpsProduct_readRows('221_會計分錄').filter(function(r){return String(r.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(r.專案ID||'')===String(data.專案ID||data.projectId||'')});var income=0,expense=0,receivable=0,payable=0;rows.forEach(function(r){var t=String(r.交易類型||'');var amt=Number(r.金額||0);if(t==='收入')income+=amt;if(t==='支出')expense+=amt;if(t==='應收')receivable+=amt;if(t==='應付')payable+=amt;});return{success:true,message:'專案損益完成。',data:{專案ID:data.專案ID||data.projectId||'',收入:income,支出:expense,應收:receivable,應付:payable,毛利:income-expense,實際損益:income-expense-payable,分錄筆數:rows.length}}}
function POAcct_year(dateStr){var m=String(dateStr||'').match(/(20\d{2})/);return m?m[1]:Utilities.formatDate(new Date(),'Asia/Taipei','yyyy')}
