/* ProjectOps ERP｜Finance Link Runtime v1
 * 記帳自動對應專案：專案ID、場次ID、活動名稱、機關、日期、描述關鍵字。
 */
function handleProjectOpsFinanceLinkAction(action,data){data=data||{};try{if(action==='project.finance.link.detectProject'||action==='財務自動對應專案')return POFinLink_detectProject(data);if(action==='project.finance.link.attachProject'||action==='財務指定專案')return POFinLink_attachProject(data);if(action==='project.finance.link.unmatchedList'||action==='待對應財務清單')return POFinLink_unmatchedList(data);if(action==='project.finance.link.repair'||action==='修復財務專案對應')return POFinLink_repair(data);if(action==='project.finance.link.summary'||action==='財務對應摘要')return POFinLink_summary(data);return null;}catch(err){return{success:false,message:'財務專案對應 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POFL_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsFinanceLinkAction(action,data);if(handled)return handled;return POFL_PREV_GATEWAY(action,data);};}
function POFL_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function POFL_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function POFL_ensure(){GovOpsProduct_ensureSheet('222_財務待對應',['待對應ID','tenantId','來源表','來源ID','描述','金額','日期','建議專案ID','建議原因','狀態','建立時間','更新時間']);}
function POFinLink_detectProject(data){POFL_ensure();var tenantId=data.tenantId||'TENANT-DEMO';var projects=POFL_read('00_專案主檔').filter(function(p){return String(p.tenantId||'')===String(tenantId)});var events=POFL_read('74_履約活動場次').filter(function(e){return !e.tenantId||String(e.tenantId)===String(tenantId)});var text=String(data.description||data.描述||data.項目||data.keyword||'');var eventId=String(data.場次ID||data.eventId||'');var projectId=String(data.專案ID||data.projectId||'');var date=String(data.date||data.日期||'');if(projectId){var p0=projects.find(function(p){return String(p.專案ID||'')===projectId});if(p0)return{success:true,message:'已依專案ID完成對應。',data:{matched:true,project:p0,reason:'專案ID'}}}
if(eventId){var ev=events.find(function(e){return String(e.場次ID||'')===eventId});if(ev){var p1=projects.find(function(p){return String(p.專案ID||'')===String(ev.專案ID||'')||String(p.標案ID||'')===String(ev.標案ID||'')||String(p.課程ID||'')===String(ev.課程ID||'')});if(p1)return{success:true,message:'已依場次ID反查專案。',data:{matched:true,project:p1,event:ev,reason:'場次ID'}}}}
var scored=[];projects.forEach(function(p){var score=0;var reasons=[];['專案名稱','主辦單位','合作單位','標案ID','課程ID'].forEach(function(k){var v=String(p[k]||'');if(v&&text.indexOf(v)>=0){score+=5;reasons.push(k)}});if(date&&(String(p.開始日期||'')<=date&&(!p.結束日期||String(p.結束日期)>=date))){score+=2;reasons.push('日期區間')}if(score>0)scored.push({project:p,score:score,reason:reasons.join(',')});});scored.sort(function(a,b){return b.score-a.score});if(scored.length)return{success:true,message:'已依描述/日期建議專案。',data:{matched:true,project:scored[0].project,reason:scored[0].reason,candidates:scored.slice(0,5)}};
var row={待對應ID:'UNMATCH-'+Utilities.getUuid().slice(0,8),tenantId:tenantId,來源表:data.來源表||'',來源ID:data.來源ID||'',描述:text,金額:Number(data.金額||data.amount||0),日期:date,建議專案ID:'',建議原因:'無法自動判斷',狀態:'待對應',建立時間:POFL_now(),更新時間:POFL_now()};GovOpsProduct_append('222_財務待對應',row);return{success:true,message:'無法自動對應，已加入待對應清單。',data:{matched:false,unmatched:row}}
function POFinLink_attachProject(data){POFL_ensure();var project=POFL_read('00_專案主檔').find(function(p){return String(p.tenantId||'')===String(data.tenantId||'TENANT-DEMO')&&String(p.專案ID||'')===String(data.專案ID||data.projectId||'')});if(!project)return{success:false,message:'找不到指定專案。',data:{}};var sourceSheet=data.來源表||data.sheet;var sourceId=data.來源ID||data.id;var idKey=data.idKey||'';if(sourceSheet&&sourceId){var rows=POFL_read(sourceSheet);var row=rows.find(function(r){return JSON.stringify(r).indexOf(String(sourceId))>=0});if(row){var patch={專案ID:project.專案ID,案源類型:project.案源類型,標案ID:project.標案ID||'',課程ID:project.課程ID||'',更新時間:POFL_now()};GovOpsProduct_update(sourceSheet,row._row,patch);}}
return{success:true,message:'財務資料已指定專案。',data:{project:project}}
}
function POFinLink_unmatchedList(data){POFL_ensure();var rows=POFL_read('222_財務待對應').filter(function(r){return (!data.tenantId||String(r.tenantId||'')===String(data.tenantId))&&String(r.狀態||'')!=='已處理'});return{success:true,message:'待對應財務清單完成。',data:{total:rows.length,rows:rows}}}
function POFinLink_repair(data){var list=POFinLink_unmatchedList(data).data.rows;var fixed=[];list.forEach(function(r){var detected=POFinLink_detectProject({tenantId:r.tenantId,description:r.描述,金額:r.金額,date:r.日期});if(detected.data&&detected.data.matched){fixed.push({unmatched:r,project:detected.data.project});try{GovOpsProduct_update('222_財務待對應',r._row,{建議專案ID:detected.data.project.專案ID,建議原因:detected.data.reason,狀態:'已建議',更新時間:POFL_now()});}catch(e){}}});return{success:true,message:'待對應財務重新比對完成。',data:{total:list.length,fixed:fixed.length,rows:fixed}}}
function POFinLink_summary(data){var un=POFinLink_unmatchedList(data).data.total;var entries=POFL_read('221_會計分錄').filter(function(r){return !data.tenantId||String(r.tenantId||'')===String(data.tenantId)});var missing=entries.filter(function(r){return !r.專案ID}).length;return{success:true,message:'財務專案對應摘要完成。',data:{會計分錄筆數:entries.length,缺專案ID分錄:missing,待對應清單:un}}}
