/* ProjectOps ERP｜Financial Report Runtime v1
 * 月報 / 季報 / 年報 / 所得稅申報資料自動彙整。
 */
function handleProjectOpsFinancialReportAction(action,data){data=data||{};try{if(action==='project.report.monthly'||action==='財務月報')return POReport_monthly(data);if(action==='project.report.quarterly'||action==='財務季報')return POReport_quarterly(data);if(action==='project.report.yearly'||action==='財務年報')return POReport_yearly(data);if(action==='project.report.incomeTax'||action==='所得稅申報資料')return POReport_incomeTax(data);if(action==='project.report.voucherList'||action==='憑證清單')return POReport_voucherList(data);if(action==='project.report.exportData'||action==='報表匯出資料')return POReport_exportData(data);return null;}catch(err){return{success:false,message:'財務報表 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POREPORT_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsFinancialReportAction(action,data);if(handled)return handled;return POREPORT_PREV_GATEWAY(action,data);};}
function PORpt_read(sheet){try{return GovOpsProduct_readRows(sheet)||[]}catch(e){return[]}}
function PORpt_tenant(row,tenantId){return !row.tenantId||String(row.tenantId)===String(tenantId)}
function PORpt_year(v){var m=String(v||'').match(/(20\d{2})/);return m?m[1]:Utilities.formatDate(new Date(),'Asia/Taipei','yyyy')}
function PORpt_month(v){var s=String(v||'');var m=s.match(/(20\d{2})[\/\-](\d{1,2})/);return m?m[1]+'-'+('0'+m[2]).slice(-2):Utilities.formatDate(new Date(),'Asia/Taipei','yyyy-MM')}
function PORpt_quarter(month){var mm=Number(String(month||'').slice(5,7)||1);return Math.ceil(mm/3)}
function PORpt_projects(tenantId){var map={};PORpt_read('00_專案主檔').filter(function(r){return PORpt_tenant(r,tenantId)}).forEach(function(p){map[String(p.專案ID||'')]=p});return map}
function PORpt_entries(data){var tenantId=data.tenantId||'TENANT-DEMO';var year=String(data.year||data.年度||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy'));return PORpt_read('221_會計分錄').filter(function(r){return PORpt_tenant(r,tenantId)&&String(r.年度||PORpt_year(r.交易日期||r.建立時間))===year});}
function PORpt_incomeExpense(entries){var income=0,expense=0,receivable=0,payable=0;var bySource={},byAccount={};entries.forEach(function(r){var amt=Number(r.金額||0);var type=String(r.交易類型||'');var source=String(r.案源類型||'未分類');var acct=type==='支出'||type==='應付'?String(r.借方科目||'其他支出'):String(r.貸方科目||'其他收入');if(type==='收入'){income+=amt;bySource[source]=(bySource[source]||0)+amt}if(type==='支出'){expense+=amt;byAccount[acct]=(byAccount[acct]||0)+amt}if(type==='應收')receivable+=amt;if(type==='應付')payable+=amt;});return{收入:income,支出:expense,應收:receivable,應付:payable,毛利:income-expense,案源別收入:bySource,科目別支出:byAccount}}
function POReport_monthly(data){var month=String(data.month||data.月份||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy-MM'));var year=month.slice(0,4);var entries=PORpt_entries(Object.assign({},data,{year:year})).filter(function(r){return PORpt_month(r.交易日期||r.建立時間)===month});var s=PORpt_incomeExpense(entries);return{success:true,message:'財務月報完成。',data:Object.assign({月份:month,分錄筆數:entries.length},s,{缺憑證:POReport_voucherList(Object.assign({},data,{year:year,month:month})).data.缺憑證.length})}}
function POReport_quarterly(data){var year=String(data.year||data.年度||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy'));var q=Number(data.quarter||data.季度||1);var entries=PORpt_entries(Object.assign({},data,{year:year})).filter(function(r){return PORpt_quarter(PORpt_month(r.交易日期||r.建立時間))===q});var s=PORpt_incomeExpense(entries);return{success:true,message:'財務季報完成。',data:Object.assign({年度:year,季度:q,分錄筆數:entries.length},s)}}
function POReport_yearly(data){var year=String(data.year||data.年度||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy'));var entries=PORpt_entries(Object.assign({},data,{year:year}));var s=PORpt_incomeExpense(entries);var voucher=POReport_voucherList(Object.assign({},data,{year:year})).data;return{success:true,message:'財務年報完成。',data:Object.assign({年度:year,分錄筆數:entries.length,憑證筆數:voucher.憑證.length,缺憑證筆數:voucher.缺憑證.length,憑證完整率:entries.length?Math.round((entries.length-voucher.缺憑證.length)/entries.length*10000)/100:0},s)}}
function POReport_incomeTax(data){var year=String(data.year||data.年度||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy'));var entries=PORpt_entries(Object.assign({},data,{year:year}));var income=entries.filter(function(r){return String(r.交易類型||'')==='收入'});var expense=entries.filter(function(r){return String(r.交易類型||'')==='支出'});var taxableExpense=expense.filter(function(r){return String(r.是否可報稅||'')==='是'&&String(r.憑證URL||'')!==''});var nonTaxableExpense=expense.filter(function(r){return String(r.是否可報稅||'')!=='是'||String(r.憑證URL||'')===''});var yearly=POReport_yearly(Object.assign({},data,{year:year})).data;return{success:true,message:'年度所得稅申報資料完成。',data:{年度:year,摘要:yearly,收入明細:income,支出明細:expense,可報稅支出明細:taxableExpense,不可報稅或缺憑證支出明細:nonTaxableExpense,憑證檢查:POReport_voucherList(Object.assign({},data,{year:year})).data}}}
function POReport_voucherList(data){var entries=PORpt_entries(data);if(data.month){entries=entries.filter(function(r){return PORpt_month(r.交易日期||r.建立時間)===String(data.month)})}var vouchers=entries.filter(function(r){return String(r.憑證URL||'')!==''});var missing=entries.filter(function(r){var type=String(r.交易類型||'');return (type==='支出'||type==='應付')&&String(r.憑證URL||'')===''});return{success:true,message:'憑證清單完成。',data:{憑證:vouchers,缺憑證:missing,total:entries.length}}}
function POReport_exportData(data){var year=String(data.year||data.年度||Utilities.formatDate(new Date(),'Asia/Taipei','yyyy'));return{success:true,message:'報表匯出資料完成。',data:{月報:POReport_monthly(Object.assign({},data,{month:data.month||year+'-01'})).data,年報:POReport_yearly(Object.assign({},data,{year:year})).data,所得稅:POReport_incomeTax(Object.assign({},data,{year:year})).data}}}
