/* ProjectOps ERP｜File Export Runtime v1
 * 結案報告 HTML / Word-like 檔案匯出到 Google Drive。
 * 說明：Apps Script 可直接建立 HTML 檔；Word 第一版採 .html 交付，可由 Google Docs/Word 開啟。
 */
function handleProjectOpsFileExportAction(action,data){data=data||{};try{if(action==='project.export.closingHtmlFile'||action==='匯出結案HTML檔')return POExport_closingHtmlFile(data);if(action==='project.export.closingWordFile'||action==='匯出結案Word檔')return POExport_closingWordFile(data);if(action==='project.export.deliveryPackageIndex'||action==='匯出交付包索引')return POExport_deliveryPackageIndex(data);return null;}catch(err){return{success:false,message:'檔案匯出 Runtime 暫時無法完成操作。',data:{error:String(err)}}}}
if(typeof handleAPIGatewayAction==='function'){var POEXPORT_PREV_GATEWAY=handleAPIGatewayAction;handleAPIGatewayAction=function(action,data){var handled=handleProjectOpsFileExportAction(action,data);if(handled)return handled;return POEXPORT_PREV_GATEWAY(action,data);};}
function POExport_now(){return Utilities.formatDate(new Date(),'Asia/Taipei','yyyy/MM/dd HH:mm:ss')}
function POExport_safeName(s){return String(s||'ProjectOps').replace(/[\\/:*?"<>|#%{}~&]/g,'_').slice(0,80)}
function POExport_project(data){if(typeof PODoc_project==='function')return PODoc_project(data);if(typeof PODetail_findProject==='function')return PODetail_findProject(data);return null}
function POExport_html(data){if(typeof PODoc_deliveryHtml==='function'){var r=PODoc_deliveryHtml(data);if(r.success)return r.data.html;}return '<html><body><pre>無法產生結案報告</pre></body></html>'}
function POExport_folder(){var name='ProjectOps_ERP_Exports';var it=DriveApp.getFoldersByName(name);return it.hasNext()?it.next():DriveApp.createFolder(name)}
function POExport_createFile(name,content,mime){var folder=POExport_folder();var file=folder.createFile(name,content,mime||MimeType.HTML);return{fileId:file.getId(),name:file.getName(),url:file.getUrl(),createdAt:POExport_now()}}
function POExport_closingHtmlFile(data){var p=POExport_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var html=POExport_html(data);var file=POExport_createFile(POExport_safeName(p.專案名稱)+'_結案報告.html',html,MimeType.HTML);return{success:true,message:'結案HTML檔已匯出至Drive。',data:{project:p,file:file}}}
function POExport_closingWordFile(data){var p=POExport_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var html=POExport_html(data);var file=POExport_createFile(POExport_safeName(p.專案名稱)+'_結案報告_可用Word開啟.html',html,MimeType.HTML);return{success:true,message:'Word可開啟版結案報告已匯出至Drive。',data:{project:p,file:file,note:'第一版以HTML格式交付，可用Word或Google Docs開啟後另存為.docx。'}}}
function POExport_deliveryPackageIndex(data){var p=POExport_project(data);if(!p)return{success:false,message:'找不到專案。',data:{}};var pkg=[];try{pkg=GovOpsProduct_readRows('212_專案交付包').filter(function(r){return String(r.tenantId||'')===String(p.tenantId)&&String(r.專案ID||'')===String(p.專案ID)})}catch(e){}var lines=[];lines.push('<h1>'+POExport_safeName(p.專案名稱)+'｜交付包索引</h1>');lines.push('<p>產生時間：'+POExport_now()+'</p>');lines.push('<ol>');pkg.forEach(function(x){lines.push('<li>'+String(x.交付項目||'附件')+'｜<a href="'+String(x.檔案URL||'#')+'">'+String(x.備註||x.檔案URL||'檔案')+'</a></li>')});lines.push('</ol>');var file=POExport_createFile(POExport_safeName(p.專案名稱)+'_交付包索引.html','<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>'+lines.join('\n')+'</body></html>',MimeType.HTML);return{success:true,message:'交付包索引已匯出至Drive。',data:{project:p,file:file,total:pkg.length}}}
