/**
 * GovOps OS｜課程執行現場管理正式後端
 * 對齊：課程執行紀錄、場地設備確認、教材與物資準備、領據管理、核銷文件管理、當日工作任務表、當日注意事項、報到處任務、餐點管理、物品清單、現場聯絡人、現場照片紀錄、課後回收檢核
 */
var GOVOPS_COURSE_OPS_SHEETS={courseRecord:'課程執行紀錄',venue:'場地設備確認',materials:'教材與物資準備',receipt:'領據管理',reimburse:'核銷文件管理',dailyTask:'當日工作任務表',notice:'當日注意事項',checkinTask:'報到處任務',meal:'餐點管理',items:'物品清單',contacts:'現場聯絡人',photos:'現場照片紀錄',postCheck:'課後回收檢核'};
var GOVOPS_COURSE_OPS_HEADERS={
courseRecord:['紀錄ID','活動ID','課程名稱','執行日期','執行狀態','講師','地點','人數','異常狀況','處理紀錄','備註','建立時間','更新時間'],
venue:['確認ID','活動ID','場地名稱','設備項目','確認狀態','負責人','確認時間','缺漏事項','處理狀態','備註','建立時間','更新時間'],
materials:['物資ID','活動ID','項目名稱','類型','數量','單位','準備狀態','負責人','完成時間','備註','建立時間','更新時間'],
receipt:['領據ID','活動ID','對象類型','對象名稱','金額','身分證/統編','銀行','帳號','戶名','領據狀態','付款狀態','備註','建立時間','更新時間'],
reimburse:['核銷文件ID','活動ID','文件類型','文件名稱','金額','文件狀態','缺件說明','Drive連結','負責人','備註','建立時間','更新時間'],
dailyTask:['任務ID','活動ID','任務名稱','任務區域','負責人','開始時間','完成時間','狀態','優先度','備註','建立時間','更新時間'],
notice:['注意事項ID','活動ID','注意事項','類型','提醒對象','重要性','狀態','備註','建立時間','更新時間'],
checkinTask:['報到任務ID','活動ID','任務名稱','負責人','所需物品','狀態','異常紀錄','備註','建立時間','更新時間'],
meal:['餐點ID','活動ID','餐點類型','廠商','數量','葷素','送達時間','確認狀態','費用','備註','建立時間','更新時間'],
items:['物品ID','活動ID','物品名稱','數量','單位','保管人','攜出狀態','回收狀態','備註','建立時間','更新時間'],
contacts:['聯絡人ID','活動ID','姓名','角色','電話','Email','單位','備註','建立時間','更新時間'],
photos:['照片ID','活動ID','照片類型','照片說明','Drive連結','拍攝者','拍攝時間','核銷可用','備註','建立時間','更新時間'],
postCheck:['檢核ID','活動ID','檢核項目','檢核狀態','負責人','完成時間','異常說明','備註','建立時間','更新時間']
};
function govopsCourseNow_(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Taipei','yyyy/MM/dd HH:mm:ss');}
function govopsCourseId_(p){return p+'-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Taipei','yyyyMMddHHmmss')+'-'+Math.floor(Math.random()*10000);}
function govopsCourseKey_(name){var map={'課程執行紀錄':'courseRecord','場地設備確認':'venue','教材與物資準備':'materials','領據管理':'receipt','核銷文件管理':'reimburse','當日工作任務表':'dailyTask','當日注意事項':'notice','報到處任務':'checkinTask','餐點管理':'meal','物品清單':'items','現場聯絡人':'contacts','現場照片紀錄':'photos','課後回收檢核':'postCheck'};return map[name]||name;}
function govopsCourseSheet_(key){key=govopsCourseKey_(key);var ss=SpreadsheetApp.getActiveSpreadsheet();var name=GOVOPS_COURSE_OPS_SHEETS[key];var headers=GOVOPS_COURSE_OPS_HEADERS[key];if(!name||!headers)throw new Error('未知的課程執行模組：'+key);var sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);var col=Math.max(sh.getLastColumn(),headers.length);var first=sh.getRange(1,1,1,col).getValues()[0].map(function(v){return String(v||'').trim();});if(first.every(function(v){return !v;})){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);}else{var missing=headers.filter(function(h){return first.indexOf(h)===-1;});if(missing.length)sh.getRange(1,first.filter(Boolean).length+1,1,missing.length).setValues([missing]);}return sh;}
function govopsCourseHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(function(v){return String(v||'').trim();});}
function govopsCourseRows_(key){var sh=govopsCourseSheet_(key);var headers=govopsCourseHeaders_(sh);var last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,sh.getLastColumn()).getValues().map(function(row,i){var o={_row:i+2};headers.forEach(function(h,idx){o[h]=row[idx];});return o;});}
function govopsCourseAppend_(key,obj){var sh=govopsCourseSheet_(key);var headers=govopsCourseHeaders_(sh);sh.appendRow(headers.map(function(h){return obj[h]!==undefined?obj[h]:'';}));return obj;}
function govopsCourseUpdate_(key,row,patch){var sh=govopsCourseSheet_(key);var headers=govopsCourseHeaders_(sh);headers.forEach(function(h,i){if(patch[h]!==undefined)sh.getRange(row,i+1).setValue(patch[h]);});}
function govopsInitCourseExecution(){Object.keys(GOVOPS_COURSE_OPS_SHEETS).forEach(function(k){govopsCourseSheet_(k);});return{success:true,message:'課程執行現場管理系統初始化完成',data:{sheets:GOVOPS_COURSE_OPS_SHEETS}};}
function govopsCreateCourseOpsRecord(params){params=params||{};var key=govopsCourseKey_(params.module||params['模組']||params['表單類型']);if(!key)return{success:false,message:'請提供模組'};var headers=GOVOPS_COURSE_OPS_HEADERS[key];if(!headers)return{success:false,message:'找不到模組：'+key};var idField=headers[0];var prefix={courseRecord:'CR',venue:'VENUE',materials:'MAT',receipt:'REC',reimburse:'RMB',dailyTask:'DTASK',notice:'NTC',checkinTask:'CHK',meal:'MEAL',items:'ITEM',contacts:'CONTACT',photos:'PHOTO',postCheck:'POST'}[key]||'OPS';var obj={};headers.forEach(function(h){if(params[h]!==undefined)obj[h]=params[h];});obj[idField]=obj[idField]||govopsCourseId_(prefix);obj['活動ID']=obj['活動ID']||params.activityId||'';obj['建立時間']=govopsCourseNow_();obj['更新時間']=govopsCourseNow_();govopsCourseAppend_(key,obj);return{success:true,message:'資料已新增：'+GOVOPS_COURSE_OPS_SHEETS[key],data:{id:obj[idField],record:obj}};}
function govopsUpdateCourseOpsRecord(params){params=params||{};var key=govopsCourseKey_(params.module||params['模組']||params['表單類型']);var id=params.id||params['ID']||params['紀錄ID']||params['確認ID']||params['物資ID']||params['領據ID']||params['核銷文件ID']||params['任務ID']||params['注意事項ID']||params['報到任務ID']||params['餐點ID']||params['物品ID']||params['聯絡人ID']||params['照片ID']||params['檢核ID'];var headers=GOVOPS_COURSE_OPS_HEADERS[key];if(!headers)return{success:false,message:'找不到模組'};if(!id)return{success:false,message:'請提供資料ID'};var idField=headers[0];var row=govopsCourseRows_(key).find(function(r){return String(r[idField])===String(id);});if(!row)return{success:false,message:'找不到資料'};var patch={};headers.forEach(function(h){if(params[h]!==undefined&&params[h]!=='')patch[h]=params[h];});patch['更新時間']=govopsCourseNow_();govopsCourseUpdate_(key,row._row,patch);return{success:true,message:'資料已修改：'+GOVOPS_COURSE_OPS_SHEETS[key],data:{id:id,updated:patch}};}
function govopsQueryCourseOpsRecord(params){params=params||{};var key=govopsCourseKey_(params.module||params['模組']||params['表單類型']);var headers=GOVOPS_COURSE_OPS_HEADERS[key];if(!headers)return{success:false,message:'找不到模組'};var kw=String(params.keyword||params.q||params['關鍵字']||'').trim();var activityId=String(params['活動ID']||params.activityId||'').trim();var rows=govopsCourseRows_(key);if(activityId)rows=rows.filter(function(r){return String(r['活動ID'])===activityId;});if(kw)rows=rows.filter(function(r){return JSON.stringify(r).indexOf(kw)>=0;});return{success:true,message:'查詢完成：'+GOVOPS_COURSE_OPS_SHEETS[key],data:{rows:rows,資料:rows,count:rows.length}};}
function govopsQuickBuildCourseDayPackage(params){params=params||{};var activityId=params['活動ID']||params.activityId;if(!activityId)return{success:false,message:'請提供活動ID'};var created=[];function add(module,obj){obj['活動ID']=activityId;var r=govopsCreateCourseOpsRecord(Object.assign({module:module},obj));created.push(r.data&&r.data.id);}add('dailyTask',{'任務名稱':'報到處 setup','任務區域':'報到處','狀態':'待執行','優先度':'高'});add('checkinTask',{'任務名稱':'學員報到與名冊確認','狀態':'待執行'});add('venue',{'設備項目':'投影／麥克風／延長線／座位','確認狀態':'待確認'});add('materials',{'項目名稱':'講義與簽到用品','類型':'教材物資','準備狀態':'待準備'});add('meal',{'餐點類型':'午餐／茶水','確認狀態':'待確認'});add('items',{'物品名稱':'簽到表、筆、名牌、收據資料','攜出狀態':'待攜出','回收狀態':'待回收'});add('notice',{'注意事項':'確認場地、講師、學員報到、餐點與拍照紀錄','類型':'現場提醒','重要性':'高','狀態':'待確認'});add('postCheck',{'檢核項目':'簽到表、照片、領據、核銷文件回收','檢核狀態':'待檢核'});return{success:true,message:'當日快速執行包已建立',data:{活動ID:activityId,建立筆數:created.length,ids:created}};}
function govopsCourseExecutionRoute(params){var action=String((params&&params.action)||'');if(action==='初始化課程執行系統')return govopsInitCourseExecution(params);if(action==='新增課程執行資料')return govopsCreateCourseOpsRecord(params);if(action==='修改課程執行資料')return govopsUpdateCourseOpsRecord(params);if(action==='查詢課程執行資料')return govopsQueryCourseOpsRecord(params);if(action==='建立當日快速執行包')return govopsQuickBuildCourseDayPackage(params);return null;}
/** 主 router 接法：var courseOpsResult=govopsCourseExecutionRoute(params); if(courseOpsResult)return jsonOutput(courseOpsResult); */
