/**
 * GovOps OS｜招生活動／報名資料庫／學員CRM／簽到表 正式後端 v2
 * 對齊：招生活動管理、報名資料庫、學員CRM、簽到表、簽到表紀錄
 */
var GOVOPS_ENROLLMENT_SHEETS={campaigns:'招生活動管理',registrations:'報名資料庫',crm:'學員CRM',attendance:'簽到表',attendanceLog:'簽到表紀錄'};
var GOVOPS_ENROLLMENT_HEADERS={campaigns:['招生活動ID','專案ID','活動ID','課程名稱','招生狀態','報名開始日','報名截止日','開課日期','招生名額','候補名額','報名連結','招生渠道','主辦單位','聯絡人','聯絡電話','備註','建立時間','更新時間'],registrations:['報名ID','招生活動ID','活動ID','姓名','電話','Email','身分別','服務單位','報名狀態','審核狀態','出席狀態','完訓狀態','報名來源','報名時間','通知狀態','備註','CRM_ID','建立時間','更新時間'],crm:['CRM_ID','姓名','電話','Email','服務單位','身分別','標籤','最近參與活動','累積報名次數','累積出席次數','累積完訓次數','是否回流學員','行銷同意','備註','建立時間','更新時間'],attendance:['簽到ID','招生活動ID','活動ID','報名ID','CRM_ID','姓名','電話','Email','服務單位','簽到狀態','簽到時間','簽名連結','備註','建立時間','更新時間'],attendanceLog:['紀錄ID','簽到ID','報名ID','活動ID','姓名','簽到狀態','操作時間','操作人','備註']};
function govopsEnrollNow_(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Taipei','yyyy/MM/dd HH:mm:ss');}
function govopsEnrollId_(p){return p+'-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Taipei','yyyyMMddHHmmss')+'-'+Math.floor(Math.random()*10000);}
function govopsEnrollSheet_(key){var ss=SpreadsheetApp.getActiveSpreadsheet();var name=GOVOPS_ENROLLMENT_SHEETS[key];var headers=GOVOPS_ENROLLMENT_HEADERS[key];var sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);var col=Math.max(sh.getLastColumn(),headers.length);var first=sh.getRange(1,1,1,col).getValues()[0].map(function(v){return String(v||'').trim();});if(first.every(function(v){return !v;})){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);}else{var missing=headers.filter(function(h){return first.indexOf(h)===-1;});if(missing.length)sh.getRange(1,first.filter(Boolean).length+1,1,missing.length).setValues([missing]);}return sh;}
function govopsEnrollHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(function(v){return String(v||'').trim();});}
function govopsEnrollRows_(key){var sh=govopsEnrollSheet_(key),headers=govopsEnrollHeaders_(sh),last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,sh.getLastColumn()).getValues().map(function(row,i){var o={_row:i+2};headers.forEach(function(h,idx){o[h]=row[idx];});return o;});}
function govopsEnrollAppend_(key,obj){var sh=govopsEnrollSheet_(key),headers=govopsEnrollHeaders_(sh);sh.appendRow(headers.map(function(h){return obj[h]!==undefined?obj[h]:'';}));return obj;}
function govopsEnrollUpdate_(key,row,patch){var sh=govopsEnrollSheet_(key),headers=govopsEnrollHeaders_(sh);headers.forEach(function(h,i){if(patch[h]!==undefined)sh.getRange(row,i+1).setValue(patch[h]);});}
function govopsInitEnrollmentSystem(){Object.keys(GOVOPS_ENROLLMENT_SHEETS).forEach(function(k){govopsEnrollSheet_(k);});return{success:true,message:'招生／報名／CRM／簽到系統初始化完成',data:{sheets:GOVOPS_ENROLLMENT_SHEETS}};}
function govopsCreateCampaign(params){params=params||{};var title=params['課程名稱']||params.courseName||params['活動名稱'];if(!title)return{success:false,message:'請填寫課程名稱'};var obj={'招生活動ID':params['招生活動ID']||govopsEnrollId_('ENR'),'專案ID':params['專案ID']||params.projectId||'','活動ID':params['活動ID']||params.activityId||'','課程名稱':title,'招生狀態':params['招生狀態']||'招生中','報名開始日':params['報名開始日']||'','報名截止日':params['報名截止日']||'','開課日期':params['開課日期']||params['活動日期']||'','招生名額':params['招生名額']||'','候補名額':params['候補名額']||'','報名連結':params['報名連結']||'','招生渠道':params['招生渠道']||'','主辦單位':params['主辦單位']||'','聯絡人':params['聯絡人']||'','聯絡電話':params['聯絡電話']||'','備註':params['備註']||'','建立時間':govopsEnrollNow_(),'更新時間':govopsEnrollNow_()};govopsEnrollAppend_('campaigns',obj);return{success:true,message:'招生活動已新增',data:{招生活動ID:obj['招生活動ID'],row:obj}};}
function govopsUpdateCampaign(params){params=params||{};var id=params['招生活動ID'];if(!id)return{success:false,message:'請提供招生活動ID'};var row=govopsEnrollRows_('campaigns').find(function(r){return String(r['招生活動ID'])===String(id);});if(!row)return{success:false,message:'找不到招生活動'};var patch={};GOVOPS_ENROLLMENT_HEADERS.campaigns.forEach(function(k){if(params[k]!==undefined&&params[k]!=='')patch[k]=params[k];});patch['更新時間']=govopsEnrollNow_();govopsEnrollUpdate_('campaigns',row._row,patch);return{success:true,message:'招生活動已修改',data:{招生活動ID:id,updated:patch}};}
function govopsQueryCampaigns(params){params=params||{};var kw=String(params.keyword||params.q||params['關鍵字']||'').trim();var rows=govopsEnrollRows_('campaigns');if(kw)rows=rows.filter(function(r){return JSON.stringify(r).indexOf(kw)>=0;});return{success:true,message:'招生活動查詢完成',data:{rows:rows,資料:rows,count:rows.length}};}
function govopsUpsertCRM_(params,activityName){var phone=String(params['電話']||params.phone||'').trim(),email=String(params['Email']||params.email||'').trim();var rows=govopsEnrollRows_('crm');var found=rows.find(function(r){return(phone&&String(r['電話'])===phone)||(email&&String(r['Email'])===email);});if(found){var reg=Number(found['累積報名次數']||0)+1;govopsEnrollUpdate_('crm',found._row,{'姓名':params['姓名']||found['姓名'],'Email':email||found['Email'],'服務單位':params['服務單位']||found['服務單位'],'身分別':params['身分別']||found['身分別'],'最近參與活動':activityName||found['最近參與活動'],'累積報名次數':reg,'是否回流學員':reg>1?'是':'否','更新時間':govopsEnrollNow_()});return found['CRM_ID'];}var id=govopsEnrollId_('CRM');govopsEnrollAppend_('crm',{'CRM_ID':id,'姓名':params['姓名']||'','電話':phone,'Email':email,'服務單位':params['服務單位']||'','身分別':params['身分別']||'','標籤':params['標籤']||'','最近參與活動':activityName||'','累積報名次數':1,'累積出席次數':0,'累積完訓次數':0,'是否回流學員':'否','行銷同意':params['行銷同意']||'是','備註':params['備註']||'','建立時間':govopsEnrollNow_(),'更新時間':govopsEnrollNow_()});return id;}
function govopsCreateRegistration(params){params=params||{};var name=params['姓名']||params.name,phone=params['電話']||params.phone;if(!name)return{success:false,message:'請填寫姓名'};if(!phone)return{success:false,message:'請填寫電話'};var campaignId=params['招生活動ID']||'';var campaign=govopsEnrollRows_('campaigns').find(function(r){return String(r['招生活動ID'])===String(campaignId);});var crmId=govopsUpsertCRM_(params,campaign?campaign['課程名稱']:'');var exists=govopsEnrollRows_('registrations').find(function(r){return String(r['招生活動ID'])===String(campaignId)&&String(r['電話'])===String(phone);});if(exists)return{success:true,message:'此活動已存在相同電話報名資料',data:{報名ID:exists['報名ID'],CRM_ID:exists['CRM_ID']}};var obj={'報名ID':govopsEnrollId_('REG'),'招生活動ID':campaignId,'活動ID':params['活動ID']||(campaign?campaign['活動ID']:''),'姓名':name,'電話':phone,'Email':params['Email']||params.email||'','身分別':params['身分別']||'','服務單位':params['服務單位']||'','報名狀態':params['報名狀態']||'已報名','審核狀態':params['審核狀態']||'待審核','出席狀態':'未簽到','完訓狀態':'未完訓','報名來源':params['報名來源']||params['來源渠道']||'','報名時間':govopsEnrollNow_(),'通知狀態':'未通知','備註':params['備註']||'','CRM_ID':crmId,'建立時間':govopsEnrollNow_(),'更新時間':govopsEnrollNow_()};govopsEnrollAppend_('registrations',obj);return{success:true,message:'報名資料已新增並同步 CRM',data:{報名ID:obj['報名ID'],CRM_ID:crmId,row:obj}};}
function govopsUpdateRegistration(params){params=params||{};var id=params['報名ID'];if(!id)return{success:false,message:'請提供報名ID'};var row=govopsEnrollRows_('registrations').find(function(r){return String(r['報名ID'])===String(id);});if(!row)return{success:false,message:'找不到報名資料'};var patch={};GOVOPS_ENROLLMENT_HEADERS.registrations.forEach(function(k){if(params[k]!==undefined&&params[k]!=='')patch[k]=params[k];});patch['更新時間']=govopsEnrollNow_();govopsEnrollUpdate_('registrations',row._row,patch);return{success:true,message:'報名資料已修改',data:{報名ID:id,updated:patch}};}
function govopsQueryRegistrations(params){params=params||{};var kw=String(params.keyword||params.q||params['關鍵字']||'').trim();var status=String(params['審核狀態']||'').trim();var rows=govopsEnrollRows_('registrations');if(status)rows=rows.filter(function(r){return String(r['審核狀態'])===status;});if(kw)rows=rows.filter(function(r){return JSON.stringify(r).indexOf(kw)>=0;});return{success:true,message:'報名資料庫查詢完成',data:{rows:rows,資料:rows,count:rows.length}};}
function govopsReviewRegistration(params){var id=params['報名ID'],status=params['審核狀態']||params.status||'已錄取';if(!id)return{success:false,message:'請提供報名ID'};return govopsUpdateRegistration({'報名ID':id,'審核狀態':status,'報名狀態':status==='候補'?'候補':(status==='不錄取'?'不錄取':'已確認')});}
function govopsBatchEmailNotice(params){params=params||{};var campaignId=params['招生活動ID']||'',status=params['審核狀態']||'';var rows=govopsEnrollRows_('registrations').filter(function(r){return(!campaignId||String(r['招生活動ID'])===String(campaignId))&&(!status||String(r['審核狀態'])===String(status));});var count=0;rows.forEach(function(r){if(r['Email']){try{MailApp.sendEmail(r['Email'],params.subject||'課程通知',params.body||('親愛的 '+r['姓名']+' 您好，這是課程通知。'));govopsEnrollUpdate_('registrations',r._row,{'通知狀態':'已通知','更新時間':govopsEnrollNow_()});count++;}catch(e){}}});return{success:true,message:'批次 Email 通知完成',data:{通知筆數:count}};}
function govopsQueryCRM(params){params=params||{};var kw=String(params.keyword||params.q||params['關鍵字']||'').trim();var rows=govopsEnrollRows_('crm');if(kw)rows=rows.filter(function(r){return JSON.stringify(r).indexOf(kw)>=0;});return{success:true,message:'學員CRM查詢完成',data:{rows:rows,學員:rows,count:rows.length}};}
function govopsUpdateCRM(params){params=params||{};var id=params['CRM_ID']||params.crmPersonId;if(!id)return{success:false,message:'請提供 CRM_ID'};var row=govopsEnrollRows_('crm').find(function(r){return String(r['CRM_ID'])===String(id);});if(!row)return{success:false,message:'找不到學員 CRM'};var patch={};GOVOPS_ENROLLMENT_HEADERS.crm.forEach(function(k){if(params[k]!==undefined&&params[k]!=='')patch[k]=params[k];});patch['更新時間']=govopsEnrollNow_();govopsEnrollUpdate_('crm',row._row,patch);return{success:true,message:'學員CRM已修改',data:{CRM_ID:id,updated:patch}};}
function govopsMarketingList(params){var rows=govopsEnrollRows_('crm').filter(function(r){return String(r['行銷同意'])==='是';});return{success:true,message:'行銷名單查詢完成',data:{rows:rows,行銷名單:rows,count:rows.length}};}
function govopsReturnStudentAnalysis(params){var rows=govopsEnrollRows_('crm').filter(function(r){return Number(r['累積報名次數']||0)>1;});return{success:true,message:'回流學員分析完成',data:{rows:rows,回流學員:rows,count:rows.length}};}
function govopsParticipationHistory(params){var crmId=params['CRM_ID']||params.crmPersonId;if(!crmId)return{success:false,message:'請提供 CRM_ID'};var regs=govopsEnrollRows_('registrations').filter(function(r){return String(r['CRM_ID'])===String(crmId);});var atts=govopsEnrollRows_('attendance').filter(function(r){return String(r['CRM_ID'])===String(crmId);});return{success:true,message:'參與歷程查詢完成',data:{報名紀錄:regs,出席紀錄:atts,rows:regs}};}
function govopsGenerateAttendanceSheet(params){var campaignId=params['招生活動ID'];if(!campaignId)return{success:false,message:'請提供招生活動ID'};var regs=govopsEnrollRows_('registrations').filter(function(r){return String(r['招生活動ID'])===String(campaignId)&&['已錄取','已確認','錄取'].indexOf(String(r['審核狀態']))>=0;});if(!regs.length)return{success:false,message:'沒有可產出簽到表的錄取名單'};var existing=govopsEnrollRows_('attendance').filter(function(a){return String(a['招生活動ID'])===String(campaignId);});var count=0;regs.forEach(function(r){if(existing.some(function(a){return String(a['報名ID'])===String(r['報名ID']);}))return;govopsEnrollAppend_('attendance',{'簽到ID':govopsEnrollId_('ATT'),'招生活動ID':campaignId,'活動ID':r['活動ID'],'報名ID':r['報名ID'],'CRM_ID':r['CRM_ID'],'姓名':r['姓名'],'電話':r['電話'],'Email':r['Email'],'服務單位':r['服務單位'],'簽到狀態':'未簽到','簽到時間':'','簽名連結':'','備註':'系統自動產出','建立時間':govopsEnrollNow_(),'更新時間':govopsEnrollNow_()});count++;});return{success:true,message:'簽到表已自動產出',data:{新增筆數:count,招生活動ID:campaignId}};}
function govopsQueryAttendance(params){params=params||{};var kw=String(params.keyword||params.q||params['關鍵字']||'').trim(),campaignId=String(params['招生活動ID']||'').trim();var rows=govopsEnrollRows_('attendance');if(campaignId)rows=rows.filter(function(r){return String(r['招生活動ID'])===campaignId;});if(kw)rows=rows.filter(function(r){return JSON.stringify(r).indexOf(kw)>=0;});return{success:true,message:'簽到表查詢完成',data:{rows:rows,簽到表:rows,count:rows.length}};}
function govopsUpdateAttendance(params){var id=params['簽到ID'];if(!id)return{success:false,message:'請提供簽到ID'};var row=govopsEnrollRows_('attendance').find(function(r){return String(r['簽到ID'])===String(id);});if(!row)return{success:false,message:'找不到簽到資料'};var status=params['簽到狀態']||'已簽到';govopsEnrollUpdate_('attendance',row._row,{'簽到狀態':status,'簽到時間':params['簽到時間']||govopsEnrollNow_(),'備註':params['備註']||row['備註'],'更新時間':govopsEnrollNow_()});govopsEnrollAppend_('attendanceLog',{'紀錄ID':govopsEnrollId_('ALOG'),'簽到ID':id,'報名ID':row['報名ID'],'活動ID':row['活動ID'],'姓名':row['姓名'],'簽到狀態':status,'操作時間':govopsEnrollNow_(),'操作人':params.userId||'system','備註':params['備註']||''});if(status==='已簽到'){var reg=govopsEnrollRows_('registrations').find(function(r){return String(r['報名ID'])===String(row['報名ID']);});if(reg)govopsEnrollUpdate_('registrations',reg._row,{'出席狀態':'已簽到','更新時間':govopsEnrollNow_()});var crm=govopsEnrollRows_('crm').find(function(c){return String(c['CRM_ID'])===String(row['CRM_ID']);});if(crm)govopsEnrollUpdate_('crm',crm._row,{'累積出席次數':Number(crm['累積出席次數']||0)+1,'更新時間':govopsEnrollNow_()});}return{success:true,message:'簽到狀態已更新',data:{簽到ID:id,狀態:status}};}
function govopsMarkCompletedTraining(params){var regId=params['報名ID'];if(!regId)return{success:false,message:'請提供報名ID'};var reg=govopsEnrollRows_('registrations').find(function(r){return String(r['報名ID'])===String(regId);});if(!reg)return{success:false,message:'找不到報名資料'};govopsEnrollUpdate_('registrations',reg._row,{'完訓狀態':'已完訓','更新時間':govopsEnrollNow_()});var crm=govopsEnrollRows_('crm').find(function(c){return String(c['CRM_ID'])===String(reg['CRM_ID']);});if(crm)govopsEnrollUpdate_('crm',crm._row,{'累積完訓次數':Number(crm['累積完訓次數']||0)+1,'更新時間':govopsEnrollNow_()});return{success:true,message:'完訓狀態已更新',data:{報名ID:regId}};}
function govopsEnrollmentRoute(params){var action=String((params&&params.action)||'');if(action==='初始化招生報名系統')return govopsInitEnrollmentSystem(params);if(action==='新增招生活動'||action==='招生設定')return govopsCreateCampaign(params);if(action==='修改招生活動')return govopsUpdateCampaign(params);if(action==='查詢招生活動')return govopsQueryCampaigns(params);if(action==='新增報名資料'||action==='新增報名'||action==='手動新增報名')return govopsCreateRegistration(params);if(action==='修改報名資料')return govopsUpdateRegistration(params);if(action==='查詢報名資料庫'||action==='學員名冊')return govopsQueryRegistrations(params);if(action==='審核報名'||action==='錄取審核'||action==='候補管理'||action==='不錄取管理')return govopsReviewRegistration(params);if(action==='批次Email通知'||action==='批次 Email 通知')return govopsBatchEmailNotice(params);if(action==='查詢學員CRM'||action==='學員資料庫')return govopsQueryCRM(params);if(action==='修改學員CRM')return govopsUpdateCRM(params);if(action==='行銷名單')return govopsMarketingList(params);if(action==='回流學員分析')return govopsReturnStudentAnalysis(params);if(action==='參與歷程'||action==='重複參課歷程')return govopsParticipationHistory(params);if(action==='累計完訓次數'||action==='更新完訓狀態')return govopsMarkCompletedTraining(params);if(action==='產出簽到表'||action==='簽到表自動產出')return govopsGenerateAttendanceSheet(params);if(action==='查詢簽到表'||action==='出席統計')return govopsQueryAttendance(params);if(action==='更新簽到狀態')return govopsUpdateAttendance(params);return null;}
/** 主 router 接法：var enrollmentResult=govopsEnrollmentRoute(params); if(enrollmentResult)return jsonOutput(enrollmentResult); */
