/**
 * GovOps AI OS｜All-In-One GAS Backend
 * Runtime：Tenant Isolation + SaaS Login Session
 */
const GOVOPS={TZ:'Asia/Taipei',SESSION_HOURS:12,SHEETS:{Tenants:'01_Tenants',Users:'02_Users',Roles:'03_Roles',Sessions:'04_Sessions',LoginLogs:'05_LoginLogs',Projects:'02_專案主檔',Activities:'03_活動課程主檔',Finance:'20_財務收支資料',Tasks:'21_任務管理',Checks:'22_檢核清單',Docs:'23_文件索引與版本',Risks:'25_AI風險警示',Daily:'26_每日戰情紀錄',Audit:'90_操作紀錄'},ROLE_PERMISSIONS:{老闆:['*'],系統管理員:['*'],專案經理:['查詢專案','新增專案','查詢活動','新增活動','查詢任務','取得Dashboard','產生今日戰情','每日AI風險檢查','檢查專案核銷缺件','判斷專案是否可請款','新增文件','查詢文件','LINE查詢'],行政人員:['查詢專案','查詢活動','新增活動','查詢任務','新增文件','查詢文件','取得Dashboard','LINE查詢'],會計人員:['查詢專案','查詢活動','新增財務','查詢財務','檢查專案核銷缺件','判斷專案是否可請款','查詢文件','新增文件','取得Dashboard','LINE查詢'],只讀人員:['查詢專案','查詢活動','查詢任務','查詢財務','查詢文件','取得Dashboard','LINE查詢']}};
function doGet(e){return jsonOut({success:true,成功:true,message:'GovOps AI OS API 已啟動',runtime:'SaaS Login Runtime',time:nowText()});}
function doPost(e){try{const body=JSON.parse(e.postData&&e.postData.contents?e.postData.contents:'{}');const action=body.action||'';const data=body.data||{};const filters=body.filters||{};let result;if(['login','logout','getSession','refreshSession','getCurrentUser','初始化系統','建立登入測試帳號','健康檢查'].indexOf(action)>=0){result=publicRoute(action,data,body);}else{const ctx=getSessionContext(body);tenantGuard(action,data,filters,ctx);roleGuard(action,ctx);result=routeAction(action,data,filters,ctx);touchSession(ctx.token);}return jsonOut(Object.assign({success:true,成功:true,action},result&&result.token?result:{result:result,結果:result}));}catch(err){return jsonOut({success:false,成功:false,error:err.message,錯誤訊息:err.message,type:'SAAS_LOGIN_RUNTIME_ERROR',time:nowText()});}}
function publicRoute(action,data,body){switch(action){case'健康檢查':return {message:'API 正常',runtime:'SaaS Login Runtime',time:nowText()};case'初始化系統':return 初始化系統();case'建立登入測試帳號':return 建立登入測試帳號(data);case'login':return login(data);case'logout':return logout(getToken(body));case'getSession':return getSessionInfo(getToken(body));case'refreshSession':return refreshSession(getToken(body));case'getCurrentUser':return getCurrentUser(getToken(body));default:throw new Error('未知公開 action：'+action);}}
function routeAction(action,data,filters,ctx){switch(action){case'取得Dashboard':return 取得Dashboard(ctx);case'產生今日戰情':return 產生今日戰情(ctx);case'每日AI風險檢查':return 每日AI風險檢查(ctx);case'新增專案':return 新增專案(data,ctx);case'查詢專案':return querySheet(GOVOPS.SHEETS.Projects,filters,ctx);case'新增活動':return 新增活動(data,ctx);case'查詢活動':return querySheet(GOVOPS.SHEETS.Activities,filters,ctx);case'查詢任務':return querySheet(GOVOPS.SHEETS.Tasks,filters,ctx);case'新增財務':return 新增財務(data,ctx);case'查詢財務':return querySheet(GOVOPS.SHEETS.Finance,filters,ctx);case'新增文件':return 新增文件(data,ctx);case'查詢文件':return querySheet(GOVOPS.SHEETS.Docs,filters,ctx);case'檢查專案核銷缺件':return 檢查專案核銷缺件(data.專案ID,ctx);case'判斷專案是否可請款':return 判斷專案是否可請款(data.專案ID,ctx);case'LINE查詢':return LINE查詢(data.文字||'',ctx);default:throw new Error('尚未支援 action：'+action);}}
function getSchemas(){const meta=['tenantId','companyCode','userId','role','createdAt','updatedAt','status'];const o={};o[GOVOPS.SHEETS.Tenants]=['tenantId','companyCode','companyName','plan','status','ownerUserId','createdAt','updatedAt'];o[GOVOPS.SHEETS.Users]=['userId','tenantId','companyCode','email','passwordHash','displayName','role','status','lastLoginAt','createdAt','updatedAt'];o[GOVOPS.SHEETS.Roles]=['roleId','tenantId','role','permissionJson','status','createdAt','updatedAt'];o[GOVOPS.SHEETS.Sessions]=['sessionId','token','tenantId','companyCode','userId','role','expiresAt','status','createdAt','lastSeenAt'];o[GOVOPS.SHEETS.LoginLogs]=['logId','tenantId','companyCode','userId','email','action','result','message','createdAt'];o[GOVOPS.SHEETS.Projects]=['專案ID','專案名稱','專案類型','機關名稱','契約編號','契約金額','履約起日','履約迄日','請款方式','專案負責人ID','專案狀態','健康分數','風險等級'].concat(meta);o[GOVOPS.SHEETS.Activities]=['活動ID','專案ID','活動名稱','活動類型','活動日期','開始時間','結束時間','活動地點','預計人數','活動狀態'].concat(meta);o[GOVOPS.SHEETS.Finance]=['財務ID','專案ID','活動ID','類型','金額','付款狀態','交易日期','說明'].concat(meta);o[GOVOPS.SHEETS.Tasks]=['任務ID','專案ID','活動ID','任務類型','任務階段','任務名稱','預計完成日','任務狀態','是否啟用','逾期提醒'].concat(meta);o[GOVOPS.SHEETS.Checks]=['檢核ID','專案ID','活動ID','檢核階段','檢核項目','是否完成','缺件說明'].concat(meta);o[GOVOPS.SHEETS.Docs]=['文件ID','專案ID','活動ID','文件類型','文件名稱','版本','檔案連結','檔案ID','是否最新版','文件狀態'].concat(meta);o[GOVOPS.SHEETS.Risks]=['風險ID','專案ID','活動ID','風險類型','風險等級','風險標題','風險說明','處理狀態'].concat(meta);o[GOVOPS.SHEETS.Daily]=['戰情ID','日期','LINE文字'].concat(meta);o[GOVOPS.SHEETS.Audit]=['紀錄ID','動作','資料表','資料ID','操作人','內容'].concat(meta);return o;}
function 初始化系統(){const schemas=getSchemas();Object.keys(schemas).forEach(n=>ensureSheet(n,schemas[n]));return{message:'初始化完成，已建立 SaaS Login Runtime 資料表與業務資料表',資料表數:Object.keys(schemas).length};}
function 建立登入測試帳號(data){初始化系統();const tenantId=data.tenantId||'tenant_demo';const companyCode=data.companyCode||'demo';const email=data.email||'admin@example.com';const password=data.password||'123456';const userId='USR_'+companyCode+'_ADMIN';if(!findOne(GOVOPS.SHEETS.Tenants,{tenantId:tenantId}))appendRaw(GOVOPS.SHEETS.Tenants,{tenantId,companyCode,companyName:data.companyName||'Demo公司',plan:data.plan||'PRO',status:'啟用',ownerUserId:userId,createdAt:nowText(),updatedAt:nowText()});if(!findOne(GOVOPS.SHEETS.Users,{tenantId:tenantId,email:email}))appendRaw(GOVOPS.SHEETS.Users,{userId,tenantId,companyCode,email,passwordHash:hashPassword(password),displayName:data.displayName||'系統管理者',role:data.role||'老闆',status:'啟用',createdAt:nowText(),updatedAt:nowText()});return{message:'登入測試帳號已建立',companyCode,email,password,提醒:'正式環境請更換密碼'};}
function login(data){const email=String(data.email||'').trim().toLowerCase();const password=String(data.password||'');const companyCode=String(data.companyCode||'').trim();if(!email||!password||!companyCode)throw new Error('請輸入 companyCode、email、password');const tenant=findOne(GOVOPS.SHEETS.Tenants,{companyCode:companyCode});if(!tenant){logLogin('',companyCode,'',email,'login','失敗','租戶不存在');throw new Error('租戶不存在');}if(tenant.status!=='啟用'){logLogin(tenant.tenantId,companyCode,'',email,'login','失敗','租戶未啟用');throw new Error('租戶未啟用');}const user=findOne(GOVOPS.SHEETS.Users,{tenantId:tenant.tenantId,email:email});if(!user){logLogin(tenant.tenantId,companyCode,'',email,'login','失敗','使用者不存在');throw new Error('使用者不存在');}if(user.status!=='啟用'){logLogin(tenant.tenantId,companyCode,user.userId,email,'login','失敗','使用者未啟用');throw new Error('使用者未啟用');}if(user.passwordHash!==hashPassword(password)){logLogin(tenant.tenantId,companyCode,user.userId,email,'login','失敗','密碼錯誤');throw new Error('帳號或密碼錯誤');}const token=makeToken();const expiresAt=addHours(nowDate(),GOVOPS.SESSION_HOURS);appendRaw(GOVOPS.SHEETS.Sessions,{sessionId:makeId('SES'),token,tenantId:tenant.tenantId,companyCode,userId:user.userId,role:user.role,expiresAt:formatDate(expiresAt),status:'啟用',createdAt:nowText(),lastSeenAt:nowText()});updateUserLastLogin(user.userId,tenant.tenantId);logLogin(tenant.tenantId,companyCode,user.userId,email,'login','成功','登入成功');return{success:true,token,tenantId:tenant.tenantId,companyCode,userId:user.userId,role:user.role,displayName:user.displayName,plan:tenant.plan,expiresAt:formatDate(expiresAt)};}
function logout(token){const s=getSessionRow(token,false);if(s){updateByKey(GOVOPS.SHEETS.Sessions,'token',token,{status:'已登出',lastSeenAt:nowText()});logLogin(s.tenantId,s.companyCode,s.userId,'','logout','成功','已登出');}return{message:'已登出'};}
function getSessionInfo(token){const s=getSessionRow(token,true);return{session:{tenantId:s.tenantId,companyCode:s.companyCode,userId:s.userId,role:s.role,expiresAt:s.expiresAt,status:s.status}};}
function refreshSession(token){const s=getSessionRow(token,true);const expiresAt=formatDate(addHours(nowDate(),GOVOPS.SESSION_HOURS));updateByKey(GOVOPS.SHEETS.Sessions,'token',token,{expiresAt,lastSeenAt:nowText()});return{message:'session 已延長',expiresAt};}
function getCurrentUser(token){const s=getSessionRow(token,true);const u=findOne(GOVOPS.SHEETS.Users,{tenantId:s.tenantId,userId:s.userId});const t=findOne(GOVOPS.SHEETS.Tenants,{tenantId:s.tenantId});return{tenantId:s.tenantId,companyCode:s.companyCode,userId:s.userId,role:s.role,displayName:u?u.displayName:'',email:u?u.email:'',companyName:t?t.companyName:'',plan:t?t.plan:''};}
function getSessionContext(body){const token=getToken(body);const s=getSessionRow(token,true);return{token,tenantId:s.tenantId,companyCode:s.companyCode,userId:s.userId,role:s.role};}
function getToken(body){const raw=body.token||body.Authorization||body.authorization||'';return String(raw).replace(/^Bearer\s+/i,'').trim();}
function getSessionRow(token,strict){if(!token){if(strict)throw new Error('尚未登入或缺少 session token');return null;}const s=findOne(GOVOPS.SHEETS.Sessions,{token:token});if(!s){if(strict)throw new Error('session 不存在，請重新登入');return null;}if(s.status!=='啟用'){if(strict)throw new Error('session 已失效，請重新登入');return null;}if(new Date(s.expiresAt).getTime()<Date.now()){updateByKey(GOVOPS.SHEETS.Sessions,'token',token,{status:'已過期'});if(strict)throw new Error('session 已過期，請重新登入');return null;}return s;}
function touchSession(token){if(token)updateByKey(GOVOPS.SHEETS.Sessions,'token',token,{lastSeenAt:nowText()});}
function tenantGuard(action,data,filters,ctx){if(!ctx.tenantId||!ctx.companyCode||!ctx.userId||!ctx.role)throw new Error('session context 不完整');if(data.tenantId||data.companyCode||data.userId||data.role)throw new Error('拒絕存取：正式版 API 不允許前端手動指定 tenantId/companyCode/userId/role');}
function roleGuard(action,ctx){const allowed=GOVOPS.ROLE_PERMISSIONS[ctx.role]||[];if(allowed.indexOf('*')>=0)return;if(allowed.indexOf(action)<0)throw new Error('權限不足：角色「'+ctx.role+'」不可執行「'+action+'」。');}
function appendRow(sheetName,data,ctx){const record=Object.assign({},data,{tenantId:ctx.tenantId,companyCode:ctx.companyCode,userId:ctx.userId,role:ctx.role,createdAt:data.createdAt||nowText(),updatedAt:nowText(),status:data.status||'啟用'});appendRaw(sheetName,record);return record;}
function querySheet(sheetName,filters,ctx){return{資料:getRows(sheetName,filters||{},ctx)}}
function getRows(sheetName,filters,ctx){const rows=readRows(sheetName);return rows.filter(o=>String(o.tenantId||'')===String(ctx.tenantId)).filter(o=>String(o.companyCode||'')===String(ctx.companyCode)).filter(o=>String(o.status||'啟用')!=='已封存').filter(o=>Object.keys(filters||{}).every(k=>!filters[k]||String(o[k])===String(filters[k])));}
function 新增專案(data,ctx){const id=makeId('PRJ');appendRow(GOVOPS.SHEETS.Projects,Object.assign({},data,{專案ID:id,健康分數:100,風險等級:'正常',專案狀態:data.專案狀態||'履約準備中'}),ctx);createProjectTasks(id,ctx);return{message:'專案已新增',專案ID:id};}
function 新增活動(data,ctx){if(!data.專案ID)throw new Error('新增活動必須選擇專案');mustOwn(GOVOPS.SHEETS.Projects,'專案ID',data.專案ID,ctx);const id=makeId('ACT');appendRow(GOVOPS.SHEETS.Activities,Object.assign({},data,{活動ID:id,活動狀態:data.活動狀態||'籌備中'}),ctx);createActivityTasks(data.專案ID,id,ctx);createChecks(data.專案ID,id,ctx);return{message:'活動已新增',活動ID:id};}
function 新增財務(data,ctx){if(data.專案ID)mustOwn(GOVOPS.SHEETS.Projects,'專案ID',data.專案ID,ctx);const id=makeId('FIN');appendRow(GOVOPS.SHEETS.Finance,Object.assign({},data,{財務ID:id}),ctx);return{message:'財務已新增',財務ID:id};}
function 新增文件(data,ctx){if(data.專案ID)mustOwn(GOVOPS.SHEETS.Projects,'專案ID',data.專案ID,ctx);const id=makeId('DOC');appendRow(GOVOPS.SHEETS.Docs,Object.assign({},data,{文件ID:id}),ctx);return{message:'文件已新增',文件ID:id};}
function createProjectTasks(projectId,ctx){['契約資料建檔','履約規格確認','請款規則確認','結案資料清單確認'].forEach((n,i)=>appendRow(GOVOPS.SHEETS.Tasks,{任務ID:makeId('TSK'),專案ID:projectId,任務類型:'專案任務',任務階段:'履約準備',任務名稱:n,預計完成日:addDays(today(),i+3),任務狀態:'未開始',是否啟用:true,逾期提醒:true},ctx));}
function createActivityTasks(projectId,activityId,ctx){['確認場地與時間','確認講師與工作人員','準備簽到表','確認餐點與物資','整理核銷資料'].forEach((n,i)=>appendRow(GOVOPS.SHEETS.Tasks,{任務ID:makeId('TSK'),專案ID:projectId,活動ID:activityId,任務類型:'活動任務',任務階段:i<4?'活動前':'活動後',任務名稱:n,預計完成日:addDays(today(),i+1),任務狀態:'未開始',是否啟用:true,逾期提醒:true},ctx));}
function createChecks(projectId,activityId,ctx){['簽到表','滿意度問卷','成果照片','講師領據','餐費發票','活動成果摘要'].forEach(n=>appendRow(GOVOPS.SHEETS.Checks,{檢核ID:makeId('CHK'),專案ID:projectId,活動ID:activityId,檢核階段:'核銷結案',檢核項目:n,是否完成:false},ctx));}
function 取得Dashboard(ctx){const projects=getRows(GOVOPS.SHEETS.Projects,{},ctx),activities=getRows(GOVOPS.SHEETS.Activities,{},ctx),tasks=getRows(GOVOPS.SHEETS.Tasks,{},ctx),finances=getRows(GOVOPS.SHEETS.Finance,{},ctx),checks=getRows(GOVOPS.SHEETS.Checks,{},ctx),risks=getRows(GOVOPS.SHEETS.Risks,{},ctx);const t=today();const overdue=tasks.filter(x=>x.預計完成日&&String(x.預計完成日)<t&&x.任務狀態!=='已完成');const todayActs=activities.filter(x=>String(x.活動日期)===t);const unpay=finances.filter(x=>['未請款','未撥款','應收款'].indexOf(x.類型)>=0);const tips=[];if(overdue.length)tips.push('目前有 '+overdue.length+' 件逾期任務。');if(unpay.length)tips.push('目前有 '+unpay.length+' 筆請款／撥款待追蹤。');if(!tips.length)tips.push('目前公司資料狀態穩定。');return{目前登入:{tenantId:ctx.tenantId,companyCode:ctx.companyCode,userId:ctx.userId,role:ctx.role},摘要:{專案數:projects.length,活動數:activities.length,今日活動數:todayActs.length,逾期任務數:overdue.length,高風險案件數:risks.length,核銷缺件數:checks.filter(x=>String(x.是否完成)!=='true').length,未完成請款數:unpay.length,風險警示數:risks.length},AI建議:tips,今日活動:todayActs,逾期任務:overdue,高風險案件:risks};}
function 每日AI風險檢查(ctx){let c=0;getRows(GOVOPS.SHEETS.Tasks,{},ctx).forEach(t=>{if(t.預計完成日&&String(t.預計完成日)<today()&&t.任務狀態!=='已完成'){appendRow(GOVOPS.SHEETS.Risks,{風險ID:makeId('RSK'),專案ID:t.專案ID,活動ID:t.活動ID,風險類型:'任務逾期',風險等級:'高風險',風險標題:'任務已逾期：'+t.任務名稱,風險說明:'請立即處理',處理狀態:'待處理'},ctx);c++;}});return{message:'AI 風險檢查完成',新增風險數:c};}
function 產生今日戰情(ctx){const d=取得Dashboard(ctx);const text=['【今日 GovOps 戰情】','公司：'+ctx.companyCode,'使用者：'+ctx.userId,'角色：'+ctx.role,'今日活動：'+d.摘要.今日活動數,'逾期任務：'+d.摘要.逾期任務數,'核銷缺件：'+d.摘要.核銷缺件數,'','AI建議：'].concat(d.AI建議.map((x,i)=>(i+1)+'. '+x)).join('\n');appendRow(GOVOPS.SHEETS.Daily,{戰情ID:makeId('DAY'),日期:today(),LINE文字:text},ctx);return{LINE文字:text,Dashboard:d};}
function 檢查專案核銷缺件(projectId,ctx){mustOwn(GOVOPS.SHEETS.Projects,'專案ID',projectId,ctx);const missing=getRows(GOVOPS.SHEETS.Checks,{專案ID:projectId},ctx).filter(x=>String(x.是否完成)!=='true').map(x=>x.檢核項目);return{專案ID:projectId,缺件數:missing.length,缺件:missing,是否完整:missing.length===0};}
function 判斷專案是否可請款(projectId,ctx){const m=檢查專案核銷缺件(projectId,ctx);return{可請款:m.缺件數===0,判斷:m.缺件數?'不可請款，仍有缺件':'可請款',缺件:m.缺件};}
function LINE查詢(text,ctx){if(String(text).indexOf('戰情')>=0||String(text).indexOf('今日')>=0)return 產生今日戰情(ctx).LINE文字;return'可查詢：今日戰情、未請款、核銷缺件。';}
function mustOwn(sheet,key,value,ctx){const r=getRows(sheet,{[key]:value},ctx)[0];if(!r)throw new Error('找不到資料，或資料不屬於目前登入公司。');return r;}
function readRows(sheetName){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);if(!sh||sh.getLastRow()<2)return[];const values=sh.getDataRange().getValues();const h=values.shift();return values.map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o;});}
function findOne(sheetName,filters){return readRows(sheetName).find(o=>Object.keys(filters).every(k=>String(o[k])===String(filters[k])));}
function appendRaw(sheetName,data){const sh=ensureSheet(sheetName,getSchemas()[sheetName]);const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];sh.appendRow(h.map(k=>data[k]!==undefined?data[k]:''));}
function updateByKey(sheetName,key,value,patch){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);if(!sh)return;const values=sh.getDataRange().getValues();const h=values[0];const idx=h.indexOf(key);for(let i=1;i<values.length;i++){if(String(values[i][idx])===String(value)){Object.keys(patch).forEach(k=>{const c=h.indexOf(k);if(c>=0)sh.getRange(i+1,c+1).setValue(patch[k]);});return;}}}
function updateUserLastLogin(userId,tenantId){updateByKey(GOVOPS.SHEETS.Users,'userId',userId,{lastLoginAt:nowText(),updatedAt:nowText()});}
function logLogin(tenantId,companyCode,userId,email,action,result,message){appendRaw(GOVOPS.SHEETS.LoginLogs,{logId:makeId('LOG'),tenantId,companyCode,userId,email,action,result,message,createdAt:nowText()});}
function hashPassword(p){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(p)));}
function makeToken(){return Utilities.getUuid().replace(/-/g,'')+'.'+Utilities.getUuid().replace(/-/g,'');}
function ensureSheet(name,headers){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);const current=sh.getRange(1,1,1,Math.max(headers.length,sh.getLastColumn()||1)).getValues()[0].filter(String);if(!current.length)sh.getRange(1,1,1,headers.length).setValues([headers]);else{const miss=headers.filter(x=>current.indexOf(x)<0);if(miss.length)sh.getRange(1,current.length+1,1,miss.length).setValues([miss]);}sh.setFrozenRows(1);return sh;}
function makeId(p){return p+Utilities.formatDate(new Date(),GOVOPS.TZ,'yyyyMMddHHmmss')+Math.floor(Math.random()*900+100);}function today(){return Utilities.formatDate(new Date(),GOVOPS.TZ,'yyyy-MM-dd');}function nowText(){return Utilities.formatDate(new Date(),GOVOPS.TZ,'yyyy-MM-dd HH:mm:ss');}function nowDate(){return new Date();}function addHours(d,h){return new Date(d.getTime()+h*60*60*1000);}function formatDate(d){return Utilities.formatDate(d,GOVOPS.TZ,'yyyy-MM-dd HH:mm:ss');}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return Utilities.formatDate(x,GOVOPS.TZ,'yyyy-MM-dd');}function jsonOut(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
